belongsTo(pig0,struct0).
belongsTo(pig1,struct7).
belongsTo(pig2,struct4).
belongsTo(stone11,struct1).
belongsTo(stone21,struct2).
belongsTo(stone23,struct2).
belongsTo(stone24,struct3).
belongsTo(stone26,struct4).
belongsTo(stone28,struct5).
belongsTo(stone30,struct6).
belongsTo(stone32,struct7).
belongsTo(stone34,struct7).
belongsTo(stone36,struct7).
belongsTo(stone38,struct7).
belongsTo(stone39,struct7).
belongsTo(stone41,struct7).
belongsTo(stone43,struct7).
belongsTo(stone45,struct7).
belongsTo(stone47,struct7).
belongsTo(wood10,struct0).
belongsTo(wood13,struct0).
belongsTo(wood15,struct0).
belongsTo(wood17,struct0).
belongsTo(wood19,struct0).
belongsTo(wood4,struct0).
belongsTo(wood6,struct0).
belongsTo(wood8,struct0).
bird(redbird3).
bird(redbird4).
bird(yellowbird5).
birdOrder(redbird3,2).
birdOrder(redbird4,1).
birdOrder(yellowbird5,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct3).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(yellowbird5,yellow).
hasForm(stone11,block).
hasForm(stone21,cube).
hasForm(stone23,cube).
hasForm(stone24,block).
hasForm(stone26,cube).
hasForm(stone28,ball).
hasForm(stone30,ball).
hasForm(stone32,bar).
hasForm(stone34,bar).
hasForm(stone36,bar).
hasForm(stone38,bar).
hasForm(stone39,block).
hasForm(stone41,bar).
hasForm(stone43,bar).
hasForm(stone45,bar).
hasForm(stone47,bar).
hasForm(wood10,bar).
hasForm(wood13,block).
hasForm(wood15,block).
hasForm(wood17,bar).
hasForm(wood19,bar).
hasForm(wood4,bar).
hasForm(wood6,bar).
hasForm(wood8,bar).
hasMaterial(stone11,stone).
hasMaterial(stone21,stone).
hasMaterial(stone23,stone).
hasMaterial(stone24,stone).
hasMaterial(stone26,stone).
hasMaterial(stone28,stone).
hasMaterial(stone30,stone).
hasMaterial(stone32,stone).
hasMaterial(stone34,stone).
hasMaterial(stone36,stone).
hasMaterial(stone38,stone).
hasMaterial(stone39,stone).
hasMaterial(stone41,stone).
hasMaterial(stone43,stone).
hasMaterial(stone45,stone).
hasMaterial(stone47,stone).
hasMaterial(wood10,wood).
hasMaterial(wood13,wood).
hasMaterial(wood15,wood).
hasMaterial(wood17,wood).
hasMaterial(wood19,wood).
hasMaterial(wood4,wood).
hasMaterial(wood6,wood).
hasMaterial(wood8,wood).
hasOrientation(stone11,horizontal).
hasOrientation(stone21,horizontal).
hasOrientation(stone23,horizontal).
hasOrientation(stone24,horizontal).
hasOrientation(stone26,horizontal).
hasOrientation(stone28,horizontal).
hasOrientation(stone30,horizontal).
hasOrientation(stone32,horizontal).
hasOrientation(stone34,horizontal).
hasOrientation(stone36,vertical).
hasOrientation(stone38,vertical).
hasOrientation(stone39,horizontal).
hasOrientation(stone41,vertical).
hasOrientation(stone43,vertical).
hasOrientation(stone45,vertical).
hasOrientation(stone47,vertical).
hasOrientation(wood10,vertical).
hasOrientation(wood13,vertical).
hasOrientation(wood15,vertical).
hasOrientation(wood17,vertical).
hasOrientation(wood19,vertical).
hasOrientation(wood4,horizontal).
hasOrientation(wood6,horizontal).
hasOrientation(wood8,vertical).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(stone11,medium).
hasSize(stone21,big).
hasSize(stone23,big).
hasSize(stone24,medium).
hasSize(stone26,big).
hasSize(stone28,medium).
hasSize(stone30,medium).
hasSize(stone32,big).
hasSize(stone34,big).
hasSize(stone36,big).
hasSize(stone38,big).
hasSize(stone39,medium).
hasSize(stone41,big).
hasSize(stone43,big).
hasSize(stone45,big).
hasSize(stone47,big).
hasSize(wood10,big).
hasSize(wood13,medium).
hasSize(wood15,medium).
hasSize(wood17,big).
hasSize(wood19,big).
hasSize(wood4,big).
hasSize(wood6,big).
hasSize(wood8,big).
hill(hill1).
hill(hill2).
isAnchorPointFor(pig2,struct4).
isAnchorPointFor(stone11,struct1).
isAnchorPointFor(stone21,struct2).
isAnchorPointFor(stone24,struct3).
isAnchorPointFor(stone28,struct5).
isAnchorPointFor(stone30,struct6).
isAnchorPointFor(stone32,struct7).
isAnchorPointFor(wood4,struct0).
isBelow(stone34,pig1).
isBelow(stone34,stone36).
isBelow(stone34,stone47).
isBelow(stone36,stone32).
isBelow(stone38,stone34).
isBelow(stone41,stone43).
isBelow(stone43,stone34).
isBelow(stone45,stone34).
isBelow(stone47,stone32).
isBelow(wood10,wood4).
isBelow(wood10,wood8).
isBelow(wood13,wood15).
isBelow(wood15,wood4).
isBelow(wood17,wood4).
isBelow(wood19,wood6).
isBelow(wood4,pig0).
isBelow(wood4,wood19).
isBelow(wood4,wood8).
isBelow(wood8,wood6).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isHittable(pig1,true).
isHittable(pig2,true).
isHittable(stone24,true).
isHittable(stone32,true).
isHittable(stone34,true).
isHittable(wood10,true).
isHittable(wood4,true).
isHittable(wood6,true).
isHittable(wood8,true).
isLeft(pig2,stone26).
isLeft(stone21,stone23).
isLeft(stone36,stone38).
isLeft(stone36,stone39).
isLeft(wood10,pig0).
isLeft(wood17,wood19).
isOn(pig0,wood4).
isOn(pig1,stone34).
isOn(pig2,ground).
isOn(stone11,ground).
isOn(stone21,hill1).
isOn(stone23,hill1).
isOn(stone24,ground).
isOn(stone26,ground).
isOn(stone28,hill2).
isOn(stone30,hill2).
isOn(stone32,stone36).
isOn(stone32,stone47).
isOn(stone34,stone38).
isOn(stone34,stone43).
isOn(stone34,stone45).
isOn(stone36,stone34).
isOn(stone38,hill2).
isOn(stone39,ground).
isOn(stone41,hill2).
isOn(stone43,stone41).
isOn(stone45,hill2).
isOn(stone47,stone34).
isOn(wood10,hill1).
isOn(wood13,hill1).
isOn(wood15,wood13).
isOn(wood17,hill1).
isOn(wood19,wood4).
isOn(wood4,wood10).
isOn(wood4,wood15).
isOn(wood4,wood17).
isOn(wood6,wood19).
isOn(wood6,wood8).
isOn(wood8,wood10).
isOn(wood8,wood4).
isOver(pig0,stone11).
isOver(pig1,stone39).
isOver(pig2,stone24).
isOver(stone30,stone34).
isRight(pig0,wood10).
isRight(stone23,stone21).
isRight(stone26,pig2).
isRight(stone38,stone36).
isRight(stone39,stone36).
isRight(wood19,wood17).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
protects(struct1,pig0).
protects(struct2,pig2).
protects(struct3,pig2).
protects(struct5,pig2).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
supports(stone21,stone23).
supports(stone23,stone21).
supports(stone26,pig2).
supports(stone36,stone38).
supports(stone36,stone39).
supports(stone38,stone36).
supports(wood10,pig0).
supports(wood17,wood19).
supports(wood19,wood17).
