belongsTo(ice12,struct0).
belongsTo(ice16,struct0).
belongsTo(ice18,struct0).
belongsTo(ice22,struct0).
belongsTo(ice24,struct3).
belongsTo(ice26,struct3).
belongsTo(ice28,struct3).
belongsTo(ice30,struct3).
belongsTo(ice32,struct3).
belongsTo(ice34,struct3).
belongsTo(ice36,struct3).
belongsTo(ice38,struct3).
belongsTo(ice40,struct3).
belongsTo(ice44,struct3).
belongsTo(ice48,struct3).
belongsTo(ice52,struct5).
belongsTo(ice58,struct5).
belongsTo(ice6,struct0).
belongsTo(ice64,struct5).
belongsTo(pig0,struct1).
belongsTo(pig1,struct4).
belongsTo(pig2,struct2).
belongsTo(stone10,struct0).
belongsTo(stone50,struct5).
belongsTo(stone60,struct5).
belongsTo(stone66,struct5).
belongsTo(stone68,struct5).
belongsTo(wood14,struct0).
belongsTo(wood20,struct0).
belongsTo(wood4,struct0).
belongsTo(wood42,struct3).
belongsTo(wood46,struct3).
belongsTo(wood54,struct5).
belongsTo(wood56,struct5).
belongsTo(wood62,struct5).
belongsTo(wood8,struct0).
bird(bluebird3).
birdOrder(bluebird3,0).
canCollapse(struct0,struct1).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
hasColor(bluebird3,blue).
hasForm(ice12,block).
hasForm(ice16,bar).
hasForm(ice18,bar).
hasForm(ice22,block).
hasForm(ice24,bar).
hasForm(ice26,bar).
hasForm(ice28,block).
hasForm(ice30,bar).
hasForm(ice32,block).
hasForm(ice34,bar).
hasForm(ice36,block).
hasForm(ice38,block).
hasForm(ice40,block).
hasForm(ice44,cube).
hasForm(ice48,block).
hasForm(ice52,bar).
hasForm(ice58,block).
hasForm(ice6,bar).
hasForm(ice64,bar).
hasForm(stone10,bar).
hasForm(stone50,cube).
hasForm(stone60,block).
hasForm(stone66,block).
hasForm(stone68,block).
hasForm(wood14,bar).
hasForm(wood20,cube).
hasForm(wood4,block).
hasForm(wood42,block).
hasForm(wood46,block).
hasForm(wood54,bar).
hasForm(wood56,bar).
hasForm(wood62,bar).
hasForm(wood8,block).
hasMaterial(ice12,glass).
hasMaterial(ice16,glass).
hasMaterial(ice18,glass).
hasMaterial(ice22,glass).
hasMaterial(ice24,glass).
hasMaterial(ice26,glass).
hasMaterial(ice28,glass).
hasMaterial(ice30,glass).
hasMaterial(ice32,glass).
hasMaterial(ice34,glass).
hasMaterial(ice36,glass).
hasMaterial(ice38,glass).
hasMaterial(ice40,glass).
hasMaterial(ice44,glass).
hasMaterial(ice48,glass).
hasMaterial(ice52,glass).
hasMaterial(ice58,glass).
hasMaterial(ice6,glass).
hasMaterial(ice64,glass).
hasMaterial(stone10,stone).
hasMaterial(stone50,stone).
hasMaterial(stone60,stone).
hasMaterial(stone66,stone).
hasMaterial(stone68,stone).
hasMaterial(wood14,wood).
hasMaterial(wood20,wood).
hasMaterial(wood4,wood).
hasMaterial(wood42,wood).
hasMaterial(wood46,wood).
hasMaterial(wood54,wood).
hasMaterial(wood56,wood).
hasMaterial(wood62,wood).
hasMaterial(wood8,wood).
hasOrientation(ice12,horizontal).
hasOrientation(ice16,horizontal).
hasOrientation(ice18,horizontal).
hasOrientation(ice22,vertical).
hasOrientation(ice24,horizontal).
hasOrientation(ice26,horizontal).
hasOrientation(ice28,vertical).
hasOrientation(ice30,horizontal).
hasOrientation(ice32,vertical).
hasOrientation(ice34,horizontal).
hasOrientation(ice36,vertical).
hasOrientation(ice38,vertical).
hasOrientation(ice40,horizontal).
hasOrientation(ice44,horizontal).
hasOrientation(ice48,vertical).
hasOrientation(ice52,horizontal).
hasOrientation(ice58,horizontal).
hasOrientation(ice6,horizontal).
hasOrientation(ice64,horizontal).
hasOrientation(stone10,horizontal).
hasOrientation(stone50,horizontal).
hasOrientation(stone60,horizontal).
hasOrientation(stone66,vertical).
hasOrientation(stone68,horizontal).
hasOrientation(wood14,horizontal).
hasOrientation(wood20,horizontal).
hasOrientation(wood4,vertical).
hasOrientation(wood42,vertical).
hasOrientation(wood46,vertical).
hasOrientation(wood54,horizontal).
hasOrientation(wood56,horizontal).
hasOrientation(wood62,horizontal).
hasOrientation(wood8,horizontal).
hasSize(ice12,medium).
hasSize(ice16,big).
hasSize(ice18,big).
hasSize(ice22,medium).
hasSize(ice24,big).
hasSize(ice26,big).
hasSize(ice28,medium).
hasSize(ice30,big).
hasSize(ice32,medium).
hasSize(ice34,big).
hasSize(ice36,medium).
hasSize(ice38,medium).
hasSize(ice40,medium).
hasSize(ice44,small).
hasSize(ice48,medium).
hasSize(ice52,big).
hasSize(ice58,medium).
hasSize(ice6,big).
hasSize(ice64,big).
hasSize(pig0,medium).
hasSize(pig1,small).
hasSize(pig2,medium).
hasSize(stone10,big).
hasSize(stone50,small).
hasSize(stone60,medium).
hasSize(stone66,medium).
hasSize(stone68,medium).
hasSize(wood14,big).
hasSize(wood20,small).
hasSize(wood4,medium).
hasSize(wood42,medium).
hasSize(wood46,medium).
hasSize(wood54,big).
hasSize(wood56,big).
hasSize(wood62,big).
hasSize(wood8,medium).
hill(hill1).
hill(hill2).
isAnchorPointFor(ice24,struct3).
isAnchorPointFor(pig0,struct1).
isAnchorPointFor(pig1,struct4).
isAnchorPointFor(pig2,struct2).
isAnchorPointFor(stone50,struct5).
isAnchorPointFor(wood4,struct0).
isBelow(ice12,ice18).
isBelow(ice16,stone10).
isBelow(ice18,wood14).
isBelow(ice24,ice28).
isBelow(ice26,ice24).
isBelow(ice26,wood42).
isBelow(ice28,ice30).
isBelow(ice30,ice32).
isBelow(ice32,ice34).
isBelow(ice34,ice36).
isBelow(ice34,ice38).
isBelow(ice34,ice48).
isBelow(ice40,wood46).
isBelow(ice44,ice40).
isBelow(ice52,stone50).
isBelow(ice52,stone66).
isBelow(ice52,stone68).
isBelow(ice58,stone60).
isBelow(ice6,ice22).
isBelow(ice6,wood20).
isBelow(ice6,wood4).
isBelow(ice64,wood56).
isBelow(stone10,ice12).
isBelow(stone60,wood62).
isBelow(wood14,ice6).
isBelow(wood42,ice44).
isBelow(wood46,ice34).
isBelow(wood46,ice48).
isBelow(wood54,ice58).
isBelow(wood56,ice52).
isBelow(wood62,ice64).
isBelow(wood8,ice16).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isHittable(ice12,true).
isHittable(ice18,true).
isHittable(ice22,true).
isHittable(ice24,true).
isHittable(ice26,true).
isHittable(ice28,true).
isHittable(ice30,true).
isHittable(ice32,true).
isHittable(ice34,true).
isHittable(ice36,true).
isHittable(ice38,true).
isHittable(ice40,true).
isHittable(ice48,true).
isHittable(ice6,true).
isHittable(pig0,true).
isHittable(wood14,true).
isHittable(wood20,true).
isHittable(wood4,true).
isHittable(wood46,true).
isHittable(wood8,true).
isLeft(ice30,ice40).
isLeft(stone50,wood56).
isLeft(wood14,ice22).
isLeft(wood4,wood14).
isOn(ice12,stone10).
isOn(ice16,wood8).
isOn(ice18,ice12).
isOn(ice22,ice6).
isOn(ice24,ice26).
isOn(ice26,hill1).
isOn(ice28,ice24).
isOn(ice30,ice28).
isOn(ice32,ice30).
isOn(ice34,ice32).
isOn(ice34,wood46).
isOn(ice36,ice34).
isOn(ice38,ice34).
isOn(ice40,ice44).
isOn(ice44,wood42).
isOn(ice48,ice34).
isOn(ice48,wood46).
isOn(ice52,wood56).
isOn(ice58,wood54).
isOn(ice6,wood14).
isOn(ice64,wood62).
isOn(pig0,hill1).
isOn(pig1,hill2).
isOn(pig2,ground).
isOn(stone10,ice16).
isOn(stone50,ice52).
isOn(stone60,ice58).
isOn(stone66,ice52).
isOn(stone68,ice52).
isOn(wood14,ice18).
isOn(wood20,ice6).
isOn(wood4,ice6).
isOn(wood42,ice26).
isOn(wood46,ice40).
isOn(wood54,hill2).
isOn(wood56,ice64).
isOn(wood62,stone60).
isOn(wood8,hill1).
isOver(pig2,ice26).
isRight(ice22,wood14).
isRight(ice40,ice30).
isRight(wood14,wood4).
isRight(wood56,stone50).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
protects(struct3,pig2).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
supports(ice22,wood14).
supports(wood4,wood14).
