belongsTo(ice14,struct2).
belongsTo(ice24,struct2).
belongsTo(ice31,struct4).
belongsTo(ice32,struct4).
belongsTo(ice40,struct4).
belongsTo(pig0,struct1).
belongsTo(stone20,struct1).
belongsTo(wood10,struct2).
belongsTo(wood12,struct2).
belongsTo(wood16,struct1).
belongsTo(wood18,struct1).
belongsTo(wood2,struct0).
belongsTo(wood22,struct1).
belongsTo(wood26,struct1).
belongsTo(wood28,struct1).
belongsTo(wood30,struct3).
belongsTo(wood34,struct5).
belongsTo(wood35,struct6).
belongsTo(wood37,struct7).
belongsTo(wood38,struct7).
belongsTo(wood4,struct1).
belongsTo(wood42,struct8).
belongsTo(wood44,struct9).
belongsTo(wood49,struct10).
belongsTo(wood50,struct11).
belongsTo(wood52,struct10).
belongsTo(wood53,struct12).
belongsTo(wood55,struct13).
belongsTo(wood6,struct1).
belongsTo(wood8,struct1).
bird(bluebird8).
bird(redbird1).
bird(redbird2).
bird(redbird3).
bird(redbird4).
bird(redbird5).
bird(redbird6).
bird(redbird7).
birdOrder(bluebird8,4).
birdOrder(redbird1,7).
birdOrder(redbird2,5).
birdOrder(redbird3,6).
birdOrder(redbird4,2).
birdOrder(redbird5,0).
birdOrder(redbird6,1).
birdOrder(redbird7,3).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct10,struct11).
canCollapse(struct10,struct9).
canCollapse(struct11,struct10).
canCollapse(struct12,struct13).
canCollapse(struct13,struct12).
canCollapse(struct2,struct1).
canCollapse(struct2,struct3).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canCollapse(struct8,struct9).
canCollapse(struct9,struct10).
canCollapse(struct9,struct8).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct11,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct12,struct13,away).
collapsesInDirection(struct13,struct12,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct10,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(bluebird8,blue).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasColor(redbird7,red).
hasForm(ice14,bar).
hasForm(ice24,bar).
hasForm(ice31,block).
hasForm(ice32,bar).
hasForm(ice40,bar).
hasForm(stone20,block).
hasForm(wood10,bar).
hasForm(wood12,bar).
hasForm(wood16,bar).
hasForm(wood18,bar).
hasForm(wood2,bar).
hasForm(wood22,bar).
hasForm(wood26,bar).
hasForm(wood28,bar).
hasForm(wood30,bar).
hasForm(wood34,bar).
hasForm(wood35,bar).
hasForm(wood37,bar).
hasForm(wood38,bar).
hasForm(wood4,bar).
hasForm(wood42,bar).
hasForm(wood44,bar).
hasForm(wood49,block).
hasForm(wood50,block).
hasForm(wood52,cube).
hasForm(wood53,bar).
hasForm(wood55,bar).
hasForm(wood6,bar).
hasForm(wood8,bar).
hasMaterial(ice14,glass).
hasMaterial(ice24,glass).
hasMaterial(ice31,glass).
hasMaterial(ice32,glass).
hasMaterial(ice40,glass).
hasMaterial(stone20,stone).
hasMaterial(wood10,wood).
hasMaterial(wood12,wood).
hasMaterial(wood16,wood).
hasMaterial(wood18,wood).
hasMaterial(wood2,wood).
hasMaterial(wood22,wood).
hasMaterial(wood26,wood).
hasMaterial(wood28,wood).
hasMaterial(wood30,wood).
hasMaterial(wood34,wood).
hasMaterial(wood35,wood).
hasMaterial(wood37,wood).
hasMaterial(wood38,wood).
hasMaterial(wood4,wood).
hasMaterial(wood42,wood).
hasMaterial(wood44,wood).
hasMaterial(wood49,wood).
hasMaterial(wood50,wood).
hasMaterial(wood52,wood).
hasMaterial(wood53,wood).
hasMaterial(wood55,wood).
hasMaterial(wood6,wood).
hasMaterial(wood8,wood).
hasOrientation(ice14,vertical).
hasOrientation(ice24,vertical).
hasOrientation(ice31,horizontal).
hasOrientation(ice32,horizontal).
hasOrientation(ice40,horizontal).
hasOrientation(stone20,vertical).
hasOrientation(wood10,horizontal).
hasOrientation(wood12,horizontal).
hasOrientation(wood16,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood2,vertical).
hasOrientation(wood22,vertical).
hasOrientation(wood26,vertical).
hasOrientation(wood28,vertical).
hasOrientation(wood30,vertical).
hasOrientation(wood34,horizontal).
hasOrientation(wood35,horizontal).
hasOrientation(wood37,horizontal).
hasOrientation(wood38,horizontal).
hasOrientation(wood4,vertical).
hasOrientation(wood42,horizontal).
hasOrientation(wood44,horizontal).
hasOrientation(wood49,vertical).
hasOrientation(wood50,horizontal).
hasOrientation(wood52,horizontal).
hasOrientation(wood53,horizontal).
hasOrientation(wood55,horizontal).
hasOrientation(wood6,horizontal).
hasOrientation(wood8,vertical).
hasSize(ice14,medium).
hasSize(ice24,medium).
hasSize(ice31,medium).
hasSize(ice32,big).
hasSize(ice40,big).
hasSize(pig0,medium).
hasSize(stone20,medium).
hasSize(wood10,big).
hasSize(wood12,medium).
hasSize(wood16,medium).
hasSize(wood18,small).
hasSize(wood2,small).
hasSize(wood22,small).
hasSize(wood26,big).
hasSize(wood28,big).
hasSize(wood30,small).
hasSize(wood34,big).
hasSize(wood35,big).
hasSize(wood37,medium).
hasSize(wood38,small).
hasSize(wood4,big).
hasSize(wood42,big).
hasSize(wood44,big).
hasSize(wood49,medium).
hasSize(wood50,medium).
hasSize(wood52,small).
hasSize(wood53,big).
hasSize(wood55,big).
hasSize(wood6,big).
hasSize(wood8,big).
hill(dummyObject).
isAnchorPointFor(ice31,struct4).
isAnchorPointFor(wood10,struct2).
isAnchorPointFor(wood2,struct0).
isAnchorPointFor(wood30,struct3).
isAnchorPointFor(wood34,struct5).
isAnchorPointFor(wood35,struct6).
isAnchorPointFor(wood37,struct7).
isAnchorPointFor(wood42,struct8).
isAnchorPointFor(wood44,struct9).
isAnchorPointFor(wood49,struct10).
isAnchorPointFor(wood50,struct11).
isAnchorPointFor(wood53,struct12).
isAnchorPointFor(wood55,struct13).
isAnchorPointFor(wood6,struct1).
isBelow(ice14,wood12).
isBelow(ice24,wood12).
isBelow(stone20,wood22).
isBelow(wood10,ice14).
isBelow(wood10,ice24).
isBelow(wood16,stone20).
isBelow(wood18,pig0).
isBelow(wood26,wood16).
isBelow(wood28,wood6).
isBelow(wood4,wood6).
isBelow(wood52,wood49).
isBelow(wood6,wood18).
isBelow(wood6,wood26).
isBelow(wood6,wood8).
isBelow(wood8,wood16).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct13).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(pig0,true).
isHittable(stone20,true).
isHittable(wood10,true).
isHittable(wood12,true).
isHittable(wood16,true).
isHittable(wood18,true).
isHittable(wood2,true).
isHittable(wood22,true).
isHittable(wood28,true).
isHittable(wood34,true).
isHittable(wood35,true).
isHittable(wood37,true).
isHittable(wood38,true).
isHittable(wood4,true).
isHittable(wood42,true).
isHittable(wood44,true).
isHittable(wood53,true).
isHittable(wood55,true).
isHittable(wood6,true).
isHittable(wood8,true).
isLeft(ice31,ice40).
isLeft(ice32,ice40).
isLeft(pig0,wood26).
isLeft(wood18,wood26).
isLeft(wood26,wood28).
isLeft(wood37,wood38).
isLeft(wood8,pig0).
isLeft(wood8,wood18).
isOn(ice14,wood10).
isOn(ice24,wood10).
isOn(ice31,ground).
isOn(ice32,ground).
isOn(ice40,ground).
isOn(pig0,wood18).
isOn(stone20,wood16).
isOn(wood10,ground).
isOn(wood12,ice14).
isOn(wood12,ice24).
isOn(wood16,wood26).
isOn(wood16,wood8).
isOn(wood18,wood6).
isOn(wood2,ground).
isOn(wood22,stone20).
isOn(wood26,wood6).
isOn(wood28,ground).
isOn(wood30,ground).
isOn(wood34,ground).
isOn(wood35,ground).
isOn(wood37,ground).
isOn(wood38,ground).
isOn(wood4,ground).
isOn(wood42,ground).
isOn(wood44,ground).
isOn(wood49,wood52).
isOn(wood50,ground).
isOn(wood52,ground).
isOn(wood53,ground).
isOn(wood55,ground).
isOn(wood6,wood28).
isOn(wood6,wood4).
isOn(wood8,wood6).
isOver(pig0,wood8).
isRight(ice40,ice31).
isRight(ice40,ice32).
isRight(pig0,wood8).
isRight(wood18,wood8).
isRight(wood26,pig0).
isRight(wood26,wood18).
isRight(wood28,wood26).
isRight(wood38,wood37).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
pig(pig0).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct13).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(wood26,pig0).
supports(wood26,wood18).
supports(wood26,wood28).
supports(wood28,wood26).
supports(wood8,pig0).
supports(wood8,wood18).
