belongsTo(ice5,struct2).
belongsTo(pig0,struct1).
belongsTo(pig1,struct0).
belongsTo(pig10,struct4).
belongsTo(pig2,struct3).
belongsTo(pig3,struct0).
belongsTo(pig4,struct0).
belongsTo(pig5,struct3).
belongsTo(pig6,struct4).
belongsTo(pig7,struct4).
belongsTo(pig8,struct4).
belongsTo(pig9,struct3).
belongsTo(stone11,struct2).
belongsTo(stone13,struct2).
belongsTo(stone15,struct2).
belongsTo(stone17,struct2).
belongsTo(stone19,struct2).
belongsTo(stone21,struct2).
belongsTo(stone23,struct2).
belongsTo(stone25,struct2).
belongsTo(stone7,struct2).
belongsTo(stone9,struct2).
bird(redbird11).
bird(redbird12).
bird(redbird13).
bird(redbird14).
birdOrder(redbird11,0).
birdOrder(redbird12,3).
birdOrder(redbird13,2).
birdOrder(redbird14,1).
canCollapse(struct0,struct1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct1).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
hasColor(redbird11,red).
hasColor(redbird12,red).
hasColor(redbird13,red).
hasColor(redbird14,red).
hasForm(ice5,block).
hasForm(stone11,block).
hasForm(stone13,cube).
hasForm(stone15,ball).
hasForm(stone17,block).
hasForm(stone19,block).
hasForm(stone21,ball).
hasForm(stone23,bar).
hasForm(stone25,block).
hasForm(stone7,block).
hasForm(stone9,ball).
hasMaterial(ice5,glass).
hasMaterial(stone11,stone).
hasMaterial(stone13,stone).
hasMaterial(stone15,stone).
hasMaterial(stone17,stone).
hasMaterial(stone19,stone).
hasMaterial(stone21,stone).
hasMaterial(stone23,stone).
hasMaterial(stone25,stone).
hasMaterial(stone7,stone).
hasMaterial(stone9,stone).
hasOrientation(ice5,horizontal).
hasOrientation(stone11,horizontal).
hasOrientation(stone13,horizontal).
hasOrientation(stone15,horizontal).
hasOrientation(stone17,vertical).
hasOrientation(stone19,horizontal).
hasOrientation(stone21,horizontal).
hasOrientation(stone23,vertical).
hasOrientation(stone25,horizontal).
hasOrientation(stone7,vertical).
hasOrientation(stone9,horizontal).
hasSize(ice5,medium).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig10,small).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(pig4,medium).
hasSize(pig5,small).
hasSize(pig6,medium).
hasSize(pig7,medium).
hasSize(pig8,medium).
hasSize(pig9,small).
hasSize(stone11,medium).
hasSize(stone13,small).
hasSize(stone15,medium).
hasSize(stone17,medium).
hasSize(stone19,medium).
hasSize(stone21,medium).
hasSize(stone23,big).
hasSize(stone25,medium).
hasSize(stone7,medium).
hasSize(stone9,medium).
hill(hill1).
hill(hill2).
hill(hill3).
isAnchorPointFor(ice5,struct2).
isAnchorPointFor(pig0,struct1).
isAnchorPointFor(pig10,struct4).
isAnchorPointFor(pig2,struct3).
isAnchorPointFor(pig3,struct0).
isBelow(ice5,stone11).
isBelow(ice5,stone7).
isBelow(pig10,pig6).
isBelow(pig9,pig2).
isBelow(pig9,pig5).
isBelow(stone11,stone15).
isBelow(stone13,stone17).
isBelow(stone15,stone13).
isBelow(stone15,stone21).
isBelow(stone15,stone9).
isBelow(stone19,stone11).
isBelow(stone19,stone23).
isBelow(stone21,stone17).
isBelow(stone23,stone25).
isBelow(stone25,stone17).
isBelow(stone25,stone21).
isBelow(stone7,stone9).
isBelow(stone9,stone13).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isHittable(ice5,true).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(pig3,true).
isHittable(pig4,true).
isHittable(stone11,true).
isHittable(stone13,true).
isHittable(stone15,true).
isHittable(stone17,true).
isHittable(stone19,true).
isHittable(stone21,true).
isHittable(stone7,true).
isHittable(stone9,true).
isLeft(pig10,pig7).
isLeft(pig3,pig4).
isLeft(pig4,pig1).
isLeft(pig6,pig7).
isLeft(pig7,pig8).
isLeft(stone11,stone23).
isLeft(stone15,stone23).
isLeft(stone15,stone25).
isLeft(stone7,stone11).
isOn(ice5,hill2).
isOn(pig0,ground).
isOn(pig1,ground).
isOn(pig10,ground).
isOn(pig2,pig9).
isOn(pig3,hill1).
isOn(pig4,ground).
isOn(pig5,pig9).
isOn(pig6,pig10).
isOn(pig7,ground).
isOn(pig8,hill3).
isOn(pig9,ground).
isOn(stone11,ice5).
isOn(stone11,stone19).
isOn(stone13,stone15).
isOn(stone13,stone9).
isOn(stone15,stone11).
isOn(stone17,stone13).
isOn(stone17,stone21).
isOn(stone17,stone25).
isOn(stone19,hill2).
isOn(stone21,stone15).
isOn(stone21,stone25).
isOn(stone23,stone19).
isOn(stone25,stone23).
isOn(stone7,ice5).
isOn(stone9,stone15).
isOn(stone9,stone7).
isOver(pig0,stone19).
isOver(pig1,pig0).
isOver(pig10,pig6).
isOver(pig2,pig0).
isOver(pig4,pig1).
isOver(pig5,pig2).
isOver(pig6,pig7).
isOver(pig8,pig7).
isOver(pig9,pig5).
isOver(stone15,stone9).
isOver(stone21,stone17).
isOver(stone9,stone13).
isRight(pig1,pig4).
isRight(pig4,pig3).
isRight(pig7,pig10).
isRight(pig7,pig6).
isRight(pig8,pig7).
isRight(stone11,stone7).
isRight(stone23,stone11).
isRight(stone23,stone15).
isRight(stone25,stone15).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig10).
pig(pig2).
pig(pig3).
pig(pig4).
pig(pig5).
pig(pig6).
pig(pig7).
pig(pig8).
pig(pig9).
protects(struct1,pig1).
protects(struct1,pig2).
protects(struct2,pig0).
protects(struct2,pig1).
protects(struct2,pig2).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
supports(stone23,stone11).
supports(stone23,stone15).
supports(stone25,stone15).
supports(stone7,stone11).
