belongsTo(pig0,struct1).
belongsTo(pig1,struct1).
belongsTo(stone15,struct2).
belongsTo(stone7,struct2).
belongsTo(stone9,struct2).
belongsTo(wood11,struct2).
belongsTo(wood13,struct2).
belongsTo(wood3,struct0).
belongsTo(wood5,struct2).
bird(redbird2).
bird(redbird3).
bird(redbird4).
bird(redbird5).
bird(redbird6).
birdOrder(redbird2,1).
birdOrder(redbird3,0).
birdOrder(redbird4,2).
birdOrder(redbird5,4).
birdOrder(redbird6,3).
canCollapse(struct0,struct1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasForm(stone15,bar).
hasForm(stone7,bar).
hasForm(stone9,bar).
hasForm(wood11,block).
hasForm(wood13,block).
hasForm(wood3,ball).
hasForm(wood5,bar).
hasMaterial(stone15,stone).
hasMaterial(stone7,stone).
hasMaterial(stone9,stone).
hasMaterial(wood11,wood).
hasMaterial(wood13,wood).
hasMaterial(wood3,wood).
hasMaterial(wood5,wood).
hasOrientation(stone15,vertical).
hasOrientation(stone7,vertical).
hasOrientation(stone9,horizontal).
hasOrientation(wood11,horizontal).
hasOrientation(wood13,horizontal).
hasOrientation(wood3,horizontal).
hasOrientation(wood5,horizontal).
hasSize(pig0,medium).
hasSize(pig1,small).
hasSize(stone15,medium).
hasSize(stone7,medium).
hasSize(stone9,medium).
hasSize(wood11,medium).
hasSize(wood13,medium).
hasSize(wood3,medium).
hasSize(wood5,big).
hill(hill1).
isAnchorPointFor(pig0,struct1).
isAnchorPointFor(wood3,struct0).
isAnchorPointFor(wood5,struct2).
isBelow(stone15,stone9).
isBelow(stone7,stone9).
isBelow(stone9,wood11).
isBelow(wood11,wood5).
isBelow(wood5,wood13).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(stone7,true).
isHittable(stone9,true).
isHittable(wood11,true).
isHittable(wood13,true).
isHittable(wood3,true).
isHittable(wood5,true).
isLeft(pig0,pig1).
isOn(pig0,ground).
isOn(pig1,ground).
isOn(stone15,ground).
isOn(stone7,ground).
isOn(stone9,stone15).
isOn(stone9,stone7).
isOn(wood11,stone9).
isOn(wood13,wood5).
isOn(wood3,hill1).
isOn(wood5,wood11).
isRight(pig1,pig0).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
supports(dummyObject,dummmyObject).
