belongsTo(ice33,struct4).
belongsTo(ice39,struct4).
belongsTo(ice50,struct4).
belongsTo(ice52,struct4).
belongsTo(ice57,struct8).
belongsTo(ice59,struct8).
belongsTo(ice63,struct8).
belongsTo(ice65,struct8).
belongsTo(pig0,struct1).
belongsTo(pig1,struct4).
belongsTo(pig2,struct8).
belongsTo(pig3,struct3).
belongsTo(pig4,struct7).
belongsTo(stone14,struct1).
belongsTo(stone22,struct1).
belongsTo(stone28,struct1).
belongsTo(stone30,struct1).
belongsTo(stone31,struct2).
belongsTo(stone35,struct4).
belongsTo(stone37,struct4).
belongsTo(stone45,struct4).
belongsTo(stone53,struct6).
belongsTo(wood10,struct0).
belongsTo(wood12,struct0).
belongsTo(wood16,struct1).
belongsTo(wood18,struct1).
belongsTo(wood20,struct0).
belongsTo(wood24,struct1).
belongsTo(wood26,struct0).
belongsTo(wood41,struct5).
belongsTo(wood43,struct5).
belongsTo(wood47,struct5).
belongsTo(wood49,struct5).
belongsTo(wood55,struct8).
belongsTo(wood61,struct8).
belongsTo(wood67,struct9).
belongsTo(wood69,struct9).
belongsTo(wood71,struct9).
belongsTo(wood73,struct9).
belongsTo(wood75,struct8).
belongsTo(wood77,struct8).
belongsTo(wood8,struct0).
bird(bluebird6).
bird(whitebird7).
bird(whitebird8).
bird(yellowbird5).
birdOrder(bluebird6,0).
birdOrder(whitebird7,3).
birdOrder(whitebird8,1).
birdOrder(yellowbird5,2).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct3).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canCollapse(struct7,struct8).
canCollapse(struct8,struct7).
canCollapse(struct8,struct9).
canCollapse(struct9,struct8).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(bluebird6,blue).
hasColor(whitebird7,white).
hasColor(whitebird8,white).
hasColor(yellowbird5,yellow).
hasForm(ice33,bar).
hasForm(ice39,bar).
hasForm(ice50,block).
hasForm(ice52,bar).
hasForm(ice57,bar).
hasForm(ice59,bar).
hasForm(ice63,cube).
hasForm(ice65,ball).
hasForm(stone14,bar).
hasForm(stone22,bar).
hasForm(stone28,bar).
hasForm(stone30,bar).
hasForm(stone31,block).
hasForm(stone35,bar).
hasForm(stone37,bar).
hasForm(stone45,ball).
hasForm(stone53,block).
hasForm(wood10,bar).
hasForm(wood12,block).
hasForm(wood16,bar).
hasForm(wood18,bar).
hasForm(wood20,block).
hasForm(wood24,ball).
hasForm(wood26,bar).
hasForm(wood41,bar).
hasForm(wood43,bar).
hasForm(wood47,block).
hasForm(wood49,bar).
hasForm(wood55,bar).
hasForm(wood61,bar).
hasForm(wood67,bar).
hasForm(wood69,bar).
hasForm(wood71,cube).
hasForm(wood73,bar).
hasForm(wood75,bar).
hasForm(wood77,bar).
hasForm(wood8,bar).
hasMaterial(ice33,glass).
hasMaterial(ice39,glass).
hasMaterial(ice50,glass).
hasMaterial(ice52,glass).
hasMaterial(ice57,glass).
hasMaterial(ice59,glass).
hasMaterial(ice63,glass).
hasMaterial(ice65,glass).
hasMaterial(stone14,stone).
hasMaterial(stone22,stone).
hasMaterial(stone28,stone).
hasMaterial(stone30,stone).
hasMaterial(stone31,stone).
hasMaterial(stone35,stone).
hasMaterial(stone37,stone).
hasMaterial(stone45,stone).
hasMaterial(stone53,stone).
hasMaterial(wood10,wood).
hasMaterial(wood12,wood).
hasMaterial(wood16,wood).
hasMaterial(wood18,wood).
hasMaterial(wood20,wood).
hasMaterial(wood24,wood).
hasMaterial(wood26,wood).
hasMaterial(wood41,wood).
hasMaterial(wood43,wood).
hasMaterial(wood47,wood).
hasMaterial(wood49,wood).
hasMaterial(wood55,wood).
hasMaterial(wood61,wood).
hasMaterial(wood67,wood).
hasMaterial(wood69,wood).
hasMaterial(wood71,wood).
hasMaterial(wood73,wood).
hasMaterial(wood75,wood).
hasMaterial(wood77,wood).
hasMaterial(wood8,wood).
hasOrientation(ice33,vertical).
hasOrientation(ice39,vertical).
hasOrientation(ice50,horizontal).
hasOrientation(ice52,vertical).
hasOrientation(ice57,horizontal).
hasOrientation(ice59,horizontal).
hasOrientation(ice63,horizontal).
hasOrientation(ice65,horizontal).
hasOrientation(stone14,vertical).
hasOrientation(stone22,vertical).
hasOrientation(stone28,vertical).
hasOrientation(stone30,vertical).
hasOrientation(stone31,horizontal).
hasOrientation(stone35,horizontal).
hasOrientation(stone37,horizontal).
hasOrientation(stone45,horizontal).
hasOrientation(stone53,horizontal).
hasOrientation(wood10,horizontal).
hasOrientation(wood12,vertical).
hasOrientation(wood16,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood20,vertical).
hasOrientation(wood24,horizontal).
hasOrientation(wood26,vertical).
hasOrientation(wood41,vertical).
hasOrientation(wood43,horizontal).
hasOrientation(wood47,vertical).
hasOrientation(wood49,vertical).
hasOrientation(wood55,vertical).
hasOrientation(wood61,vertical).
hasOrientation(wood67,horizontal).
hasOrientation(wood69,vertical).
hasOrientation(wood71,horizontal).
hasOrientation(wood73,vertical).
hasOrientation(wood75,vertical).
hasOrientation(wood77,vertical).
hasOrientation(wood8,vertical).
hasSize(ice33,big).
hasSize(ice39,big).
hasSize(ice50,medium).
hasSize(ice52,big).
hasSize(ice57,big).
hasSize(ice59,big).
hasSize(ice63,big).
hasSize(ice65,medium).
hasSize(pig0,medium).
hasSize(pig1,big).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(pig4,medium).
hasSize(stone14,big).
hasSize(stone22,big).
hasSize(stone28,big).
hasSize(stone30,big).
hasSize(stone31,medium).
hasSize(stone35,big).
hasSize(stone37,big).
hasSize(stone45,medium).
hasSize(stone53,medium).
hasSize(wood10,big).
hasSize(wood12,medium).
hasSize(wood16,big).
hasSize(wood18,big).
hasSize(wood20,medium).
hasSize(wood24,medium).
hasSize(wood26,big).
hasSize(wood41,big).
hasSize(wood43,big).
hasSize(wood47,medium).
hasSize(wood49,big).
hasSize(wood55,big).
hasSize(wood61,big).
hasSize(wood67,big).
hasSize(wood69,big).
hasSize(wood71,big).
hasSize(wood73,big).
hasSize(wood75,big).
hasSize(wood77,big).
hasSize(wood8,big).
hill(hill2).
hill(hill3).
hill(hill4).
hill(hill5).
hill(hill6).
isAnchorPointFor(ice33,struct4).
isAnchorPointFor(pig3,struct3).
isAnchorPointFor(pig4,struct7).
isAnchorPointFor(stone14,struct1).
isAnchorPointFor(stone31,struct2).
isAnchorPointFor(stone53,struct6).
isAnchorPointFor(wood12,struct0).
isAnchorPointFor(wood43,struct5).
isAnchorPointFor(wood55,struct8).
isAnchorPointFor(wood67,struct9).
isBelow(ice33,ice39).
isBelow(ice33,stone35).
isBelow(ice39,stone37).
isBelow(ice50,stone35).
isBelow(ice52,stone37).
isBelow(ice57,pig2).
isBelow(ice57,wood61).
isBelow(ice57,wood77).
isBelow(ice59,ice63).
isBelow(ice59,ice65).
isBelow(ice63,ice65).
isBelow(stone14,wood16).
isBelow(stone22,wood18).
isBelow(stone28,wood16).
isBelow(stone30,wood18).
isBelow(stone35,ice39).
isBelow(stone35,ice52).
isBelow(stone35,pig1).
isBelow(stone37,stone45).
isBelow(wood10,wood12).
isBelow(wood10,wood20).
isBelow(wood16,pig0).
isBelow(wood16,stone22).
isBelow(wood16,stone30).
isBelow(wood18,wood24).
isBelow(wood26,wood10).
isBelow(wood26,wood20).
isBelow(wood41,wood43).
isBelow(wood41,wood47).
isBelow(wood43,wood47).
isBelow(wood49,wood43).
isBelow(wood49,wood47).
isBelow(wood55,ice57).
isBelow(wood61,ice59).
isBelow(wood61,ice63).
isBelow(wood67,wood71).
isBelow(wood69,wood67).
isBelow(wood69,wood71).
isBelow(wood73,wood67).
isBelow(wood73,wood71).
isBelow(wood75,ice57).
isBelow(wood77,ice59).
isBelow(wood8,wood10).
isBelow(wood8,wood12).
isBelow(wood8,wood20).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(ice33,true).
isHittable(ice39,true).
isHittable(ice50,true).
isHittable(ice52,true).
isHittable(ice57,true).
isHittable(ice59,true).
isHittable(ice63,true).
isHittable(ice65,true).
isHittable(pig0,true).
isHittable(pig4,true).
isHittable(stone14,true).
isHittable(stone22,true).
isHittable(stone35,true).
isHittable(stone37,true).
isHittable(stone45,true).
isHittable(stone53,true).
isHittable(wood10,true).
isHittable(wood12,true).
isHittable(wood16,true).
isHittable(wood18,true).
isHittable(wood20,true).
isHittable(wood24,true).
isHittable(wood41,true).
isHittable(wood43,true).
isHittable(wood47,true).
isHittable(wood49,true).
isHittable(wood55,true).
isHittable(wood61,true).
isHittable(wood67,true).
isHittable(wood71,true).
isHittable(wood8,true).
isLeft(ice33,pig1).
isLeft(ice39,pig1).
isLeft(stone30,stone28).
isLeft(wood12,wood20).
isOn(ice33,hill4).
isOn(ice39,ice33).
isOn(ice39,stone35).
isOn(ice50,hill4).
isOn(ice52,stone35).
isOn(ice57,wood55).
isOn(ice57,wood75).
isOn(ice59,wood61).
isOn(ice59,wood77).
isOn(ice63,ice59).
isOn(ice63,wood61).
isOn(ice65,ice59).
isOn(ice65,ice63).
isOn(pig0,wood16).
isOn(pig1,stone35).
isOn(pig2,ice57).
isOn(pig3,ground).
isOn(pig4,ground).
isOn(stone14,hill3).
isOn(stone22,wood16).
isOn(stone28,hill3).
isOn(stone30,wood16).
isOn(stone31,ground).
isOn(stone35,ice33).
isOn(stone35,ice50).
isOn(stone37,ice39).
isOn(stone37,ice52).
isOn(stone45,stone37).
isOn(stone53,ground).
isOn(wood10,wood26).
isOn(wood10,wood8).
isOn(wood12,wood10).
isOn(wood12,wood8).
isOn(wood16,stone14).
isOn(wood16,stone28).
isOn(wood18,stone22).
isOn(wood18,stone30).
isOn(wood20,wood10).
isOn(wood20,wood26).
isOn(wood20,wood8).
isOn(wood24,wood18).
isOn(wood26,ground).
isOn(wood41,ground).
isOn(wood43,wood41).
isOn(wood43,wood49).
isOn(wood47,wood41).
isOn(wood47,wood43).
isOn(wood47,wood49).
isOn(wood49,ground).
isOn(wood55,hill5).
isOn(wood61,ice57).
isOn(wood67,wood69).
isOn(wood67,wood73).
isOn(wood69,ground).
isOn(wood71,wood67).
isOn(wood71,wood69).
isOn(wood71,wood73).
isOn(wood73,ground).
isOn(wood75,hill5).
isOn(wood77,ice57).
isOn(wood8,ground).
isOver(pig0,wood18).
isOver(pig1,ice39).
isOver(pig2,wood61).
isOver(pig3,stone31).
isOver(pig4,stone53).
isRight(pig1,ice33).
isRight(pig1,ice39).
isRight(stone28,stone30).
isRight(wood20,wood12).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
pig(pig4).
protects(struct2,pig3).
protects(struct6,pig4).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(ice33,pig1).
supports(ice39,pig1).
supports(stone28,stone30).
supports(stone30,stone28).
supports(wood12,wood20).
supports(wood20,wood12).
