belongsTo(pig0,struct3).
belongsTo(pig1,struct0).
belongsTo(pig2,struct1).
belongsTo(pig3,struct2).
belongsTo(stone10,struct1).
belongsTo(stone14,struct2).
belongsTo(stone18,struct3).
belongsTo(stone6,struct0).
belongsTo(wood12,struct2).
belongsTo(wood16,struct3).
belongsTo(wood4,struct0).
belongsTo(wood8,struct1).
bird(redbird4).
bird(redbird5).
bird(redbird6).
bird(redbird7).
bird(redbird8).
birdOrder(redbird4,0).
birdOrder(redbird5,3).
birdOrder(redbird6,2).
birdOrder(redbird7,1).
birdOrder(redbird8,4).
canCollapse(struct0,struct1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct3).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasColor(redbird7,red).
hasColor(redbird8,red).
hasForm(stone10,bar).
hasForm(stone14,bar).
hasForm(stone18,bar).
hasForm(stone6,bar).
hasForm(wood12,bar).
hasForm(wood16,bar).
hasForm(wood4,bar).
hasForm(wood8,bar).
hasMaterial(stone10,stone).
hasMaterial(stone14,stone).
hasMaterial(stone18,stone).
hasMaterial(stone6,stone).
hasMaterial(wood12,wood).
hasMaterial(wood16,wood).
hasMaterial(wood4,wood).
hasMaterial(wood8,wood).
hasOrientation(stone10,vertical).
hasOrientation(stone14,vertical).
hasOrientation(stone18,vertical).
hasOrientation(stone6,vertical).
hasOrientation(wood12,horizontal).
hasOrientation(wood16,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood8,horizontal).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,small).
hasSize(pig3,medium).
hasSize(stone10,medium).
hasSize(stone14,medium).
hasSize(stone18,big).
hasSize(stone6,medium).
hasSize(wood12,medium).
hasSize(wood16,medium).
hasSize(wood4,medium).
hasSize(wood8,medium).
hill(hill2).
isAnchorPointFor(wood12,struct2).
isAnchorPointFor(wood16,struct3).
isAnchorPointFor(wood4,struct0).
isAnchorPointFor(wood8,struct1).
isBelow(stone10,wood8).
isBelow(stone14,wood12).
isBelow(stone18,wood16).
isBelow(stone6,wood4).
isBelow(wood12,pig3).
isBelow(wood16,pig0).
isBelow(wood4,pig1).
isBelow(wood8,pig2).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(pig2,true).
isHittable(pig3,true).
isHittable(stone10,true).
isHittable(stone14,true).
isHittable(stone18,true).
isHittable(stone6,true).
isHittable(wood12,true).
isHittable(wood16,true).
isHittable(wood4,true).
isHittable(wood8,true).
isLeft(dummyObject,dummmyObject).
isOn(pig0,wood16).
isOn(pig1,wood4).
isOn(pig2,wood8).
isOn(pig3,wood12).
isOn(stone10,hill2).
isOn(stone14,hill2).
isOn(stone18,hill2).
isOn(stone6,hill2).
isOn(wood12,stone14).
isOn(wood16,stone18).
isOn(wood4,stone6).
isOn(wood8,stone10).
isRight(dummyObject,dummmyObject).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
supports(dummyObject,dummmyObject).
