belongsTo(ice13,struct0).
belongsTo(ice19,struct0).
belongsTo(ice29,struct1).
belongsTo(ice31,struct1).
belongsTo(ice39,struct1).
belongsTo(ice9,struct0).
belongsTo(pig0,struct1).
belongsTo(pig1,struct0).
belongsTo(stone17,struct0).
belongsTo(stone25,struct1).
belongsTo(stone27,struct1).
belongsTo(stone35,struct1).
belongsTo(stone5,struct0).
belongsTo(stone7,struct0).
belongsTo(wood11,struct0).
belongsTo(wood15,struct0).
belongsTo(wood21,struct0).
belongsTo(wood23,struct1).
belongsTo(wood33,struct1).
belongsTo(wood37,struct1).
bird(redbird2).
bird(redbird3).
bird(redbird4).
bird(redbird5).
birdOrder(redbird2,0).
birdOrder(redbird3,2).
birdOrder(redbird4,3).
birdOrder(redbird5,1).
canCollapse(struct0,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasForm(ice13,bar).
hasForm(ice19,block).
hasForm(ice29,bar).
hasForm(ice31,bar).
hasForm(ice39,bar).
hasForm(ice9,block).
hasForm(stone17,bar).
hasForm(stone25,bar).
hasForm(stone27,bar).
hasForm(stone35,block).
hasForm(stone5,bar).
hasForm(stone7,bar).
hasForm(wood11,cube).
hasForm(wood15,cube).
hasForm(wood21,cube).
hasForm(wood23,cube).
hasForm(wood33,cube).
hasForm(wood37,cube).
hasMaterial(ice13,glass).
hasMaterial(ice19,glass).
hasMaterial(ice29,glass).
hasMaterial(ice31,glass).
hasMaterial(ice39,glass).
hasMaterial(ice9,glass).
hasMaterial(stone17,stone).
hasMaterial(stone25,stone).
hasMaterial(stone27,stone).
hasMaterial(stone35,stone).
hasMaterial(stone5,stone).
hasMaterial(stone7,stone).
hasMaterial(wood11,wood).
hasMaterial(wood15,wood).
hasMaterial(wood21,wood).
hasMaterial(wood23,wood).
hasMaterial(wood33,wood).
hasMaterial(wood37,wood).
hasOrientation(ice13,horizontal).
hasOrientation(ice19,vertical).
hasOrientation(ice29,vertical).
hasOrientation(ice31,horizontal).
hasOrientation(ice39,vertical).
hasOrientation(ice9,vertical).
hasOrientation(stone17,horizontal).
hasOrientation(stone25,horizontal).
hasOrientation(stone27,horizontal).
hasOrientation(stone35,horizontal).
hasOrientation(stone5,horizontal).
hasOrientation(stone7,horizontal).
hasOrientation(wood11,horizontal).
hasOrientation(wood15,horizontal).
hasOrientation(wood21,horizontal).
hasOrientation(wood23,horizontal).
hasOrientation(wood33,horizontal).
hasOrientation(wood37,horizontal).
hasSize(ice13,big).
hasSize(ice19,medium).
hasSize(ice29,big).
hasSize(ice31,big).
hasSize(ice39,big).
hasSize(ice9,medium).
hasSize(pig0,small).
hasSize(pig1,small).
hasSize(stone17,big).
hasSize(stone25,big).
hasSize(stone27,big).
hasSize(stone35,medium).
hasSize(stone5,big).
hasSize(stone7,big).
hasSize(wood11,small).
hasSize(wood15,small).
hasSize(wood21,small).
hasSize(wood23,small).
hasSize(wood33,small).
hasSize(wood37,small).
hill(hill1).
hill(hill2).
hill(hill3).
isAnchorPointFor(stone7,struct0).
isAnchorPointFor(wood23,struct1).
isBelow(ice13,wood11).
isBelow(ice13,wood15).
isBelow(ice13,wood21).
isBelow(ice19,ice13).
isBelow(ice29,ice31).
isBelow(ice31,wood23).
isBelow(ice31,wood33).
isBelow(ice31,wood37).
isBelow(ice39,ice31).
isBelow(ice9,ice13).
isBelow(stone17,stone7).
isBelow(stone25,stone27).
isBelow(stone27,ice29).
isBelow(stone27,ice39).
isBelow(stone27,pig0).
isBelow(stone35,ice39).
isBelow(stone35,stone27).
isBelow(stone5,stone7).
isBelow(stone7,ice19).
isBelow(stone7,ice9).
isBelow(stone7,pig1).
isCollapsable(struct0).
isCollapsable(struct1).
isHittable(ice13,true).
isHittable(ice19,true).
isHittable(ice29,true).
isHittable(ice31,true).
isHittable(ice9,true).
isHittable(stone17,true).
isHittable(stone25,true).
isHittable(stone27,true).
isHittable(stone5,true).
isHittable(stone7,true).
isHittable(wood11,true).
isHittable(wood15,true).
isHittable(wood21,true).
isHittable(wood23,true).
isHittable(wood33,true).
isHittable(wood37,true).
isLeft(stone25,stone35).
isLeft(stone5,stone17).
isOn(ice13,ice19).
isOn(ice13,ice9).
isOn(ice19,stone7).
isOn(ice29,stone27).
isOn(ice31,ice29).
isOn(ice31,ice39).
isOn(ice39,stone27).
isOn(ice39,stone35).
isOn(ice9,stone7).
isOn(pig0,stone27).
isOn(pig1,stone7).
isOn(stone17,hill1).
isOn(stone25,hill2).
isOn(stone27,stone25).
isOn(stone27,stone35).
isOn(stone35,hill2).
isOn(stone5,hill1).
isOn(stone7,stone17).
isOn(stone7,stone5).
isOn(wood11,ice13).
isOn(wood15,ice13).
isOn(wood21,ice13).
isOn(wood23,ice31).
isOn(wood33,ice31).
isOn(wood37,ice31).
isOver(pig0,ice31).
isOver(pig1,ice13).
isRight(stone17,stone5).
isRight(stone35,stone25).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
supports(dummyObject,dummmyObject).
