belongsTo(ice15,struct0).
belongsTo(ice35,struct10).
belongsTo(ice36,struct10).
belongsTo(ice44,struct10).
belongsTo(pig0,struct3).
belongsTo(pig1,struct9).
belongsTo(pig2,struct6).
belongsTo(pig3,struct5).
belongsTo(pig4,struct5).
belongsTo(stone11,struct0).
belongsTo(stone21,struct1).
belongsTo(stone27,struct2).
belongsTo(stone28,struct3).
belongsTo(stone30,struct4).
belongsTo(stone32,struct7).
belongsTo(stone34,struct8).
belongsTo(stone7,struct0).
belongsTo(stone9,struct0).
belongsTo(tnt60,struct4).
belongsTo(tnt61,struct7).
belongsTo(wood13,struct0).
belongsTo(wood17,struct0).
belongsTo(wood19,struct0).
belongsTo(wood23,struct2).
belongsTo(wood25,struct2).
belongsTo(wood38,struct11).
belongsTo(wood39,struct12).
belongsTo(wood41,struct13).
belongsTo(wood42,struct13).
belongsTo(wood46,struct14).
belongsTo(wood48,struct15).
belongsTo(wood5,struct0).
belongsTo(wood53,struct16).
belongsTo(wood54,struct17).
belongsTo(wood56,struct16).
belongsTo(wood57,struct18).
belongsTo(wood59,struct19).
bird(bluebird11).
bird(redbird10).
bird(redbird5).
bird(redbird6).
bird(redbird7).
bird(redbird8).
bird(redbird9).
birdOrder(bluebird11,4).
birdOrder(redbird10,3).
birdOrder(redbird5,5).
birdOrder(redbird6,6).
birdOrder(redbird7,2).
birdOrder(redbird8,0).
birdOrder(redbird9,1).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct10,struct11).
canCollapse(struct11,struct10).
canCollapse(struct11,struct12).
canCollapse(struct12,struct11).
canCollapse(struct12,struct13).
canCollapse(struct13,struct12).
canCollapse(struct14,struct15).
canCollapse(struct15,struct14).
canCollapse(struct15,struct16).
canCollapse(struct16,struct15).
canCollapse(struct16,struct17).
canCollapse(struct17,struct16).
canCollapse(struct18,struct19).
canCollapse(struct19,struct18).
canCollapse(struct2,struct1).
canCollapse(struct2,struct3).
canCollapse(struct3,struct4).
canCollapse(struct4,struct3).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canCollapse(struct7,struct8).
canCollapse(struct8,struct9).
canCollapse(struct9,struct10).
canCollapse(struct9,struct8).
canExplode(tnt60,pig0).
canExplode(tnt60,pig1).
canExplode(tnt60,pig2).
canExplode(tnt60,pig3).
canExplode(tnt60,pig4).
canExplode(tnt60,stone28).
canExplode(tnt60,stone30).
canExplode(tnt60,stone32).
canExplode(tnt60,stone34).
canExplode(tnt60,tnt61).
canExplode(tnt60,wood38).
canExplode(tnt60,wood39).
canExplode(tnt60,wood41).
canExplode(tnt60,wood42).
canExplode(tnt60,wood46).
canExplode(tnt60,wood48).
canExplode(tnt60,wood53).
canExplode(tnt60,wood54).
canExplode(tnt60,wood56).
canExplode(tnt60,wood57).
canExplode(tnt60,wood59).
canExplode(tnt61,ice15).
canExplode(tnt61,pig0).
canExplode(tnt61,pig1).
canExplode(tnt61,stone11).
canExplode(tnt61,stone27).
canExplode(tnt61,stone28).
canExplode(tnt61,stone30).
canExplode(tnt61,stone32).
canExplode(tnt61,stone7).
canExplode(tnt61,stone9).
canExplode(tnt61,tnt60).
canExplode(tnt61,wood13).
canExplode(tnt61,wood17).
canExplode(tnt61,wood19).
canExplode(tnt61,wood23).
canExplode(tnt61,wood25).
canExplode(tnt61,wood38).
canExplode(tnt61,wood39).
canExplode(tnt61,wood41).
canExplode(tnt61,wood42).
canExplode(tnt61,wood46).
canExplode(tnt61,wood48).
canExplode(tnt61,wood53).
canExplode(tnt61,wood54).
canExplode(tnt61,wood56).
canExplode(tnt61,wood57).
canExplode(tnt61,wood59).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct11,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct12,struct13,away).
collapsesInDirection(struct13,struct12,towards).
collapsesInDirection(struct13,struct14,away).
collapsesInDirection(struct14,struct13,towards).
collapsesInDirection(struct14,struct15,away).
collapsesInDirection(struct15,struct14,towards).
collapsesInDirection(struct15,struct16,away).
collapsesInDirection(struct16,struct15,towards).
collapsesInDirection(struct16,struct17,away).
collapsesInDirection(struct17,struct16,towards).
collapsesInDirection(struct17,struct18,away).
collapsesInDirection(struct18,struct17,towards).
collapsesInDirection(struct18,struct19,away).
collapsesInDirection(struct19,struct18,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct10,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(bluebird11,blue).
hasColor(redbird10,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasColor(redbird7,red).
hasColor(redbird8,red).
hasColor(redbird9,red).
hasForm(ice15,cube).
hasForm(ice35,block).
hasForm(ice36,bar).
hasForm(ice44,bar).
hasForm(stone11,cube).
hasForm(stone21,ball).
hasForm(stone27,block).
hasForm(stone28,block).
hasForm(stone30,cube).
hasForm(stone32,ball).
hasForm(stone34,cube).
hasForm(stone7,cube).
hasForm(stone9,cube).
hasForm(wood13,block).
hasForm(wood17,block).
hasForm(wood19,block).
hasForm(wood23,bar).
hasForm(wood25,cube).
hasForm(wood38,bar).
hasForm(wood39,bar).
hasForm(wood41,bar).
hasForm(wood42,bar).
hasForm(wood46,bar).
hasForm(wood48,bar).
hasForm(wood5,block).
hasForm(wood53,block).
hasForm(wood54,block).
hasForm(wood56,cube).
hasForm(wood57,bar).
hasForm(wood59,bar).
hasMaterial(ice15,glass).
hasMaterial(ice35,glass).
hasMaterial(ice36,glass).
hasMaterial(ice44,glass).
hasMaterial(stone11,stone).
hasMaterial(stone21,stone).
hasMaterial(stone27,stone).
hasMaterial(stone28,stone).
hasMaterial(stone30,stone).
hasMaterial(stone32,stone).
hasMaterial(stone34,stone).
hasMaterial(stone7,stone).
hasMaterial(stone9,stone).
hasMaterial(tnt60,tnt).
hasMaterial(tnt61,tnt).
hasMaterial(wood13,wood).
hasMaterial(wood17,wood).
hasMaterial(wood19,wood).
hasMaterial(wood23,wood).
hasMaterial(wood25,wood).
hasMaterial(wood38,wood).
hasMaterial(wood39,wood).
hasMaterial(wood41,wood).
hasMaterial(wood42,wood).
hasMaterial(wood46,wood).
hasMaterial(wood48,wood).
hasMaterial(wood5,wood).
hasMaterial(wood53,wood).
hasMaterial(wood54,wood).
hasMaterial(wood56,wood).
hasMaterial(wood57,wood).
hasMaterial(wood59,wood).
hasOrientation(ice15,horizontal).
hasOrientation(ice35,horizontal).
hasOrientation(ice36,horizontal).
hasOrientation(ice44,horizontal).
hasOrientation(stone11,horizontal).
hasOrientation(stone21,horizontal).
hasOrientation(stone27,vertical).
hasOrientation(stone28,horizontal).
hasOrientation(stone30,horizontal).
hasOrientation(stone32,horizontal).
hasOrientation(stone34,horizontal).
hasOrientation(stone7,horizontal).
hasOrientation(stone9,horizontal).
hasOrientation(wood13,horizontal).
hasOrientation(wood17,vertical).
hasOrientation(wood19,vertical).
hasOrientation(wood23,vertical).
hasOrientation(wood25,horizontal).
hasOrientation(wood38,horizontal).
hasOrientation(wood39,horizontal).
hasOrientation(wood41,horizontal).
hasOrientation(wood42,horizontal).
hasOrientation(wood46,horizontal).
hasOrientation(wood48,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood53,vertical).
hasOrientation(wood54,horizontal).
hasOrientation(wood56,horizontal).
hasOrientation(wood57,horizontal).
hasOrientation(wood59,horizontal).
hasSize(ice15,small).
hasSize(ice35,medium).
hasSize(ice36,big).
hasSize(ice44,big).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(pig3,small).
hasSize(pig4,medium).
hasSize(stone11,small).
hasSize(stone21,medium).
hasSize(stone27,medium).
hasSize(stone28,medium).
hasSize(stone30,small).
hasSize(stone32,medium).
hasSize(stone34,small).
hasSize(stone7,small).
hasSize(stone9,small).
hasSize(tnt60,medium).
hasSize(tnt61,small).
hasSize(wood13,medium).
hasSize(wood17,medium).
hasSize(wood19,medium).
hasSize(wood23,medium).
hasSize(wood25,small).
hasSize(wood38,big).
hasSize(wood39,big).
hasSize(wood41,medium).
hasSize(wood42,small).
hasSize(wood46,big).
hasSize(wood48,big).
hasSize(wood5,medium).
hasSize(wood53,medium).
hasSize(wood54,medium).
hasSize(wood56,small).
hasSize(wood57,big).
hasSize(wood59,big).
hill(hill2).
hill(hill3).
isAnchorPointFor(ice35,struct10).
isAnchorPointFor(pig1,struct9).
isAnchorPointFor(pig2,struct6).
isAnchorPointFor(pig3,struct5).
isAnchorPointFor(stone21,struct1).
isAnchorPointFor(stone28,struct3).
isAnchorPointFor(stone34,struct8).
isAnchorPointFor(tnt60,struct4).
isAnchorPointFor(tnt61,struct7).
isAnchorPointFor(wood23,struct2).
isAnchorPointFor(wood38,struct11).
isAnchorPointFor(wood39,struct12).
isAnchorPointFor(wood41,struct13).
isAnchorPointFor(wood46,struct14).
isAnchorPointFor(wood48,struct15).
isAnchorPointFor(wood5,struct0).
isAnchorPointFor(wood53,struct16).
isAnchorPointFor(wood54,struct17).
isAnchorPointFor(wood57,struct18).
isAnchorPointFor(wood59,struct19).
isBelow(pig0,stone28).
isBelow(stone11,wood13).
isBelow(stone7,stone9).
isBelow(stone7,wood19).
isBelow(stone9,stone11).
isBelow(wood13,ice15).
isBelow(wood17,stone9).
isBelow(wood17,wood19).
isBelow(wood19,wood13).
isBelow(wood25,stone27).
isBelow(wood5,stone7).
isBelow(wood56,wood53).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct13).
isCollapsable(struct14).
isCollapsable(struct15).
isCollapsable(struct16).
isCollapsable(struct17).
isCollapsable(struct18).
isCollapsable(struct19).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(ice15,true).
isHittable(pig0,true).
isHittable(stone11,true).
isHittable(stone27,true).
isHittable(stone28,true).
isHittable(stone32,true).
isHittable(stone7,true).
isHittable(stone9,true).
isHittable(tnt60,true).
isHittable(wood13,true).
isHittable(wood19,true).
isHittable(wood23,true).
isHittable(wood25,true).
isHittable(wood38,true).
isHittable(wood39,true).
isHittable(wood41,true).
isHittable(wood42,true).
isHittable(wood46,true).
isHittable(wood5,true).
isLeft(ice35,ice44).
isLeft(ice36,ice44).
isLeft(pig3,pig4).
isLeft(stone11,wood19).
isLeft(stone7,wood17).
isLeft(stone9,wood19).
isLeft(tnt60,stone30).
isLeft(tnt61,stone32).
isLeft(wood23,stone27).
isLeft(wood23,wood25).
isLeft(wood41,wood42).
isLeft(wood5,wood17).
isOn(ice15,wood13).
isOn(ice35,ground).
isOn(ice36,ground).
isOn(ice44,ground).
isOn(pig0,hill3).
isOn(pig1,ground).
isOn(pig2,ground).
isOn(pig3,ground).
isOn(pig4,ground).
isOn(stone11,stone9).
isOn(stone21,hill2).
isOn(stone27,wood25).
isOn(stone28,pig0).
isOn(stone30,ground).
isOn(stone32,ground).
isOn(stone34,ground).
isOn(stone7,wood5).
isOn(stone9,stone7).
isOn(stone9,wood17).
isOn(tnt60,ground).
isOn(tnt61,ground).
isOn(wood13,stone11).
isOn(wood13,wood19).
isOn(wood17,ground).
isOn(wood19,stone7).
isOn(wood19,wood17).
isOn(wood23,hill3).
isOn(wood25,hill3).
isOn(wood38,ground).
isOn(wood39,ground).
isOn(wood41,ground).
isOn(wood42,ground).
isOn(wood46,ground).
isOn(wood48,ground).
isOn(wood5,ground).
isOn(wood53,wood56).
isOn(wood54,ground).
isOn(wood56,ground).
isOn(wood57,ground).
isOn(wood59,ground).
isOver(pig0,stone28).
isOver(pig1,stone34).
isOver(pig2,stone32).
isOver(stone21,wood5).
isOver(stone32,stone34).
isRight(ice44,ice35).
isRight(ice44,ice36).
isRight(pig4,pig3).
isRight(stone27,wood23).
isRight(stone30,tnt60).
isRight(stone32,tnt61).
isRight(wood17,stone7).
isRight(wood17,wood5).
isRight(wood19,stone11).
isRight(wood19,stone9).
isRight(wood25,wood23).
isRight(wood42,wood41).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
pig(pig4).
protects(struct4,pig0).
protects(struct7,pig2).
protects(struct8,pig1).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct13).
structure(struct14).
structure(struct15).
structure(struct16).
structure(struct17).
structure(struct18).
structure(struct19).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(stone27,wood23).
supports(wood17,stone7).
supports(wood17,wood5).
supports(wood19,stone11).
supports(wood19,stone9).
supports(wood23,stone27).
supports(wood23,wood25).
