belongsTo(pig0,struct2).
belongsTo(pig1,struct1).
belongsTo(pig2,struct4).
belongsTo(pig3,struct5).
belongsTo(pig4,struct6).
belongsTo(stone12,struct0).
belongsTo(stone16,struct0).
belongsTo(stone20,struct0).
belongsTo(stone24,struct0).
belongsTo(stone28,struct0).
belongsTo(stone32,struct2).
belongsTo(stone34,struct2).
belongsTo(stone36,struct2).
belongsTo(stone40,struct2).
belongsTo(stone44,struct2).
belongsTo(stone46,struct3).
belongsTo(stone48,struct3).
belongsTo(stone50,struct3).
belongsTo(stone52,struct3).
belongsTo(stone54,struct3).
belongsTo(stone56,struct3).
belongsTo(stone58,struct3).
belongsTo(stone6,struct0).
belongsTo(wood10,struct0).
belongsTo(wood14,struct0).
belongsTo(wood18,struct0).
belongsTo(wood22,struct0).
belongsTo(wood26,struct0).
belongsTo(wood30,struct2).
belongsTo(wood38,struct2).
belongsTo(wood4,struct0).
belongsTo(wood42,struct2).
belongsTo(wood8,struct0).
bird(redbird5).
bird(yellowbird6).
birdOrder(redbird5,1).
birdOrder(yellowbird6,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct1).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct5).
canCollapse(struct5,struct6).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
hasColor(redbird5,red).
hasColor(yellowbird6,yellow).
hasForm(stone12,bar).
hasForm(stone16,ball).
hasForm(stone20,block).
hasForm(stone24,block).
hasForm(stone28,block).
hasForm(stone32,block).
hasForm(stone34,block).
hasForm(stone36,ball).
hasForm(stone40,block).
hasForm(stone44,cube).
hasForm(stone46,block).
hasForm(stone48,ball).
hasForm(stone50,cube).
hasForm(stone52,ball).
hasForm(stone54,cube).
hasForm(stone56,ball).
hasForm(stone58,ball).
hasForm(stone6,bar).
hasForm(wood10,cube).
hasForm(wood14,cube).
hasForm(wood18,bar).
hasForm(wood22,block).
hasForm(wood26,cube).
hasForm(wood30,block).
hasForm(wood38,block).
hasForm(wood4,cube).
hasForm(wood42,block).
hasForm(wood8,bar).
hasMaterial(stone12,stone).
hasMaterial(stone16,stone).
hasMaterial(stone20,stone).
hasMaterial(stone24,stone).
hasMaterial(stone28,stone).
hasMaterial(stone32,stone).
hasMaterial(stone34,stone).
hasMaterial(stone36,stone).
hasMaterial(stone40,stone).
hasMaterial(stone44,stone).
hasMaterial(stone46,stone).
hasMaterial(stone48,stone).
hasMaterial(stone50,stone).
hasMaterial(stone52,stone).
hasMaterial(stone54,stone).
hasMaterial(stone56,stone).
hasMaterial(stone58,stone).
hasMaterial(stone6,stone).
hasMaterial(wood10,wood).
hasMaterial(wood14,wood).
hasMaterial(wood18,wood).
hasMaterial(wood22,wood).
hasMaterial(wood26,wood).
hasMaterial(wood30,wood).
hasMaterial(wood38,wood).
hasMaterial(wood4,wood).
hasMaterial(wood42,wood).
hasMaterial(wood8,wood).
hasOrientation(stone12,horizontal).
hasOrientation(stone16,horizontal).
hasOrientation(stone20,horizontal).
hasOrientation(stone24,vertical).
hasOrientation(stone28,vertical).
hasOrientation(stone32,vertical).
hasOrientation(stone34,horizontal).
hasOrientation(stone36,horizontal).
hasOrientation(stone40,horizontal).
hasOrientation(stone44,horizontal).
hasOrientation(stone46,horizontal).
hasOrientation(stone48,horizontal).
hasOrientation(stone50,horizontal).
hasOrientation(stone52,horizontal).
hasOrientation(stone54,horizontal).
hasOrientation(stone56,horizontal).
hasOrientation(stone58,horizontal).
hasOrientation(stone6,horizontal).
hasOrientation(wood10,horizontal).
hasOrientation(wood14,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood22,vertical).
hasOrientation(wood26,horizontal).
hasOrientation(wood30,vertical).
hasOrientation(wood38,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood42,vertical).
hasOrientation(wood8,horizontal).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(pig3,big).
hasSize(pig4,big).
hasSize(stone12,big).
hasSize(stone16,medium).
hasSize(stone20,medium).
hasSize(stone24,medium).
hasSize(stone28,medium).
hasSize(stone32,medium).
hasSize(stone34,medium).
hasSize(stone36,medium).
hasSize(stone40,medium).
hasSize(stone44,big).
hasSize(stone46,medium).
hasSize(stone48,medium).
hasSize(stone50,big).
hasSize(stone52,medium).
hasSize(stone54,big).
hasSize(stone56,medium).
hasSize(stone58,medium).
hasSize(stone6,big).
hasSize(wood10,big).
hasSize(wood14,big).
hasSize(wood18,big).
hasSize(wood22,medium).
hasSize(wood26,big).
hasSize(wood30,medium).
hasSize(wood38,medium).
hasSize(wood4,big).
hasSize(wood42,medium).
hasSize(wood8,big).
hill(hill1).
hill(hill2).
isAnchorPointFor(pig1,struct1).
isAnchorPointFor(pig2,struct4).
isAnchorPointFor(pig3,struct5).
isAnchorPointFor(pig4,struct6).
isAnchorPointFor(stone46,struct3).
isAnchorPointFor(wood30,struct2).
isAnchorPointFor(wood4,struct0).
isBelow(pig0,stone34).
isBelow(stone12,wood14).
isBelow(stone12,wood18).
isBelow(stone20,stone6).
isBelow(stone20,wood22).
isBelow(stone24,stone20).
isBelow(stone28,stone16).
isBelow(stone32,stone34).
isBelow(stone34,stone40).
isBelow(stone34,wood30).
isBelow(stone40,stone44).
isBelow(stone44,stone36).
isBelow(stone46,stone48).
isBelow(stone48,stone52).
isBelow(stone50,stone48).
isBelow(stone50,stone56).
isBelow(stone54,stone48).
isBelow(stone54,stone56).
isBelow(stone56,stone52).
isBelow(stone6,stone28).
isBelow(stone6,wood4).
isBelow(wood10,stone6).
isBelow(wood14,wood8).
isBelow(wood18,stone24).
isBelow(wood18,wood8).
isBelow(wood22,stone28).
isBelow(wood26,wood18).
isBelow(wood30,stone36).
isBelow(wood38,pig0).
isBelow(wood38,wood42).
isBelow(wood4,stone16).
isBelow(wood42,stone40).
isBelow(wood8,stone20).
isBelow(wood8,wood10).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isHittable(pig1,true).
isHittable(stone12,true).
isHittable(stone16,true).
isHittable(stone20,true).
isHittable(stone24,true).
isHittable(stone28,true).
isHittable(stone32,true).
isHittable(stone34,true).
isHittable(stone6,true).
isHittable(wood10,true).
isHittable(wood14,true).
isHittable(wood30,true).
isHittable(wood4,true).
isHittable(wood8,true).
isLeft(pig0,wood42).
isLeft(stone12,wood26).
isLeft(stone32,pig0).
isLeft(stone32,wood38).
isLeft(stone34,wood42).
isLeft(stone46,stone50).
isLeft(stone50,stone54).
isLeft(stone54,stone58).
isLeft(stone56,stone58).
isLeft(stone6,wood22).
isLeft(wood10,stone20).
isLeft(wood14,wood18).
isLeft(wood30,stone40).
isLeft(wood8,stone24).
isOn(pig0,wood38).
isOn(pig1,hill1).
isOn(pig2,hill1).
isOn(pig3,ground).
isOn(pig4,ground).
isOn(stone12,hill1).
isOn(stone16,stone28).
isOn(stone16,wood4).
isOn(stone20,stone24).
isOn(stone20,wood8).
isOn(stone24,wood18).
isOn(stone28,stone6).
isOn(stone28,wood22).
isOn(stone32,hill1).
isOn(stone34,pig0).
isOn(stone34,stone32).
isOn(stone36,stone44).
isOn(stone36,wood30).
isOn(stone40,stone34).
isOn(stone40,wood42).
isOn(stone44,stone40).
isOn(stone46,hill1).
isOn(stone48,stone46).
isOn(stone48,stone50).
isOn(stone48,stone54).
isOn(stone50,hill1).
isOn(stone52,stone48).
isOn(stone52,stone56).
isOn(stone54,hill1).
isOn(stone56,stone50).
isOn(stone56,stone54).
isOn(stone58,hill1).
isOn(stone6,stone20).
isOn(stone6,wood10).
isOn(wood10,wood8).
isOn(wood14,stone12).
isOn(wood18,stone12).
isOn(wood18,wood26).
isOn(wood22,stone20).
isOn(wood26,hill1).
isOn(wood30,stone34).
isOn(wood38,hill1).
isOn(wood4,stone6).
isOn(wood42,wood38).
isOn(wood8,wood14).
isOn(wood8,wood18).
isOver(pig0,stone32).
isOver(pig1,wood30).
isOver(stone48,stone52).
isOver(stone56,stone52).
isOver(stone58,stone54).
isRight(pig0,stone32).
isRight(stone20,wood10).
isRight(stone24,wood8).
isRight(stone40,wood30).
isRight(stone50,stone46).
isRight(stone54,stone50).
isRight(stone58,stone54).
isRight(stone58,stone56).
isRight(wood18,wood14).
isRight(wood22,stone6).
isRight(wood26,stone12).
isRight(wood38,stone32).
isRight(wood42,pig0).
isRight(wood42,stone34).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
pig(pig4).
protects(struct2,pig1).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
supports(stone24,wood8).
supports(stone32,pig0).
supports(stone32,wood38).
supports(stone40,wood30).
supports(stone50,stone46).
supports(stone50,stone54).
supports(stone54,stone50).
supports(stone54,stone58).
supports(wood22,stone6).
supports(wood30,stone40).
supports(wood42,pig0).
supports(wood42,stone34).
