belongsTo(ice19,struct3).
belongsTo(ice3,struct1).
belongsTo(pig0,struct1).
belongsTo(pig1,struct3).
belongsTo(pig2,struct0).
belongsTo(pig3,struct4).
belongsTo(stone11,struct2).
belongsTo(stone13,struct2).
belongsTo(stone15,struct3).
belongsTo(stone5,struct1).
belongsTo(stone9,struct2).
belongsTo(wood17,struct3).
belongsTo(wood7,struct1).
bird(redbird4).
bird(redbird5).
bird(redbird6).
bird(redbird7).
birdOrder(redbird4,0).
birdOrder(redbird5,3).
birdOrder(redbird6,2).
birdOrder(redbird7,1).
canCollapse(struct0,struct1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct3).
canCollapse(struct3,struct4).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasColor(redbird7,red).
hasForm(ice19,block).
hasForm(ice3,cube).
hasForm(stone11,cube).
hasForm(stone13,ball).
hasForm(stone15,block).
hasForm(stone5,block).
hasForm(stone9,block).
hasForm(wood17,cube).
hasForm(wood7,block).
hasMaterial(ice19,glass).
hasMaterial(ice3,glass).
hasMaterial(stone11,stone).
hasMaterial(stone13,stone).
hasMaterial(stone15,stone).
hasMaterial(stone5,stone).
hasMaterial(stone9,stone).
hasMaterial(wood17,wood).
hasMaterial(wood7,wood).
hasOrientation(ice19,vertical).
hasOrientation(ice3,horizontal).
hasOrientation(stone11,horizontal).
hasOrientation(stone13,horizontal).
hasOrientation(stone15,vertical).
hasOrientation(stone5,horizontal).
hasOrientation(stone9,horizontal).
hasOrientation(wood17,horizontal).
hasOrientation(wood7,vertical).
hasSize(ice19,medium).
hasSize(ice3,small).
hasSize(pig0,medium).
hasSize(pig1,small).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(stone11,big).
hasSize(stone13,medium).
hasSize(stone15,medium).
hasSize(stone5,medium).
hasSize(stone9,medium).
hasSize(wood17,small).
hasSize(wood7,medium).
hill(hill1).
isAnchorPointFor(ice3,struct1).
isAnchorPointFor(pig1,struct3).
isAnchorPointFor(pig2,struct0).
isAnchorPointFor(pig3,struct4).
isAnchorPointFor(stone11,struct2).
isBelow(pig0,wood7).
isBelow(pig1,wood17).
isBelow(stone13,stone11).
isBelow(stone15,wood17).
isBelow(stone5,wood7).
isBelow(wood17,ice19).
isBelow(wood7,ice3).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isHittable(ice19,true).
isHittable(ice3,true).
isHittable(pig2,true).
isHittable(stone11,true).
isHittable(stone5,true).
isHittable(stone9,true).
isHittable(wood17,true).
isHittable(wood7,true).
isLeft(pig1,stone15).
isLeft(stone5,pig0).
isLeft(stone9,stone13).
isOn(ice19,wood17).
isOn(ice3,wood7).
isOn(pig0,hill1).
isOn(pig1,hill1).
isOn(pig2,hill1).
isOn(pig3,hill1).
isOn(stone11,stone13).
isOn(stone13,hill1).
isOn(stone15,hill1).
isOn(stone5,hill1).
isOn(stone9,hill1).
isOn(wood17,pig1).
isOn(wood17,stone15).
isOn(wood7,pig0).
isOn(wood7,stone5).
isOver(pig0,stone5).
isOver(pig1,stone15).
isOver(stone13,stone9).
isRight(pig0,stone5).
isRight(stone13,stone9).
isRight(stone15,pig1).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
supports(stone15,pig1).
supports(stone9,stone13).
