belongsTo(pig0,struct0).
belongsTo(pig1,struct1).
belongsTo(pig2,struct2).
belongsTo(pig3,struct3).
belongsTo(stone1,struct0).
belongsTo(stone3,struct1).
belongsTo(stone5,struct2).
belongsTo(stone7,struct3).
belongsTo(wood0,struct0).
belongsTo(wood2,struct1).
belongsTo(wood4,struct2).
belongsTo(wood6,struct3).
bird(redbird0).
bird(redbird1).
bird(redbird2).
bird(redbird3).
bird(redbird4).
birdOrder(redbird0,4).
birdOrder(redbird1,3).
birdOrder(redbird2,2).
birdOrder(redbird3,1).
birdOrder(redbird4,0).
canCollapse(struct1,struct0).
canCollapse(struct2,struct1).
canCollapse(struct3,struct2).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct3,struct2,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasForm(stone1,bar).
hasForm(stone3,bar).
hasForm(stone5,bar).
hasForm(stone7,bar).
hasForm(wood0,bar).
hasForm(wood2,bar).
hasForm(wood4,bar).
hasForm(wood6,bar).
hasMaterial(stone1,stone).
hasMaterial(stone3,stone).
hasMaterial(stone5,stone).
hasMaterial(stone7,stone).
hasMaterial(wood0,wood).
hasMaterial(wood2,wood).
hasMaterial(wood4,wood).
hasMaterial(wood6,wood).
hasOrientation(stone1,vertical).
hasOrientation(stone3,vertical).
hasOrientation(stone5,vertical).
hasOrientation(stone7,vertical).
hasOrientation(wood0,horizontal).
hasOrientation(wood2,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood6,horizontal).
hasSize(pig0,small).
hasSize(pig1,small).
hasSize(pig2,small).
hasSize(pig3,small).
hasSize(stone1,medium).
hasSize(stone3,medium).
hasSize(stone5,medium).
hasSize(stone7,big).
hasSize(wood0,medium).
hasSize(wood2,medium).
hasSize(wood4,medium).
hasSize(wood6,medium).
hill(hill0).
isBelow(stone1,wood0).
isBelow(stone3,wood2).
isBelow(stone5,wood4).
isBelow(stone7,wood6).
isBelow(wood0,pig0).
isBelow(wood2,pig1).
isBelow(wood4,pig2).
isBelow(wood6,pig3).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(pig2,true).
isHittable(pig3,true).
isHittable(stone1,true).
isHittable(stone3,true).
isHittable(stone5,true).
isHittable(stone7,true).
isHittable(wood0,true).
isHittable(wood2,true).
isHittable(wood4,true).
isHittable(wood6,true).
isOn(pig0,wood0).
isOn(pig1,wood2).
isOn(pig2,wood4).
isOn(pig3,wood6).
isOn(stone1,hill0).
isOn(stone3,hill0).
isOn(stone5,hill0).
isOn(stone7,hill0).
isOn(wood0,stone1).
isOn(wood2,stone3).
isOn(wood4,stone5).
isOn(wood6,stone7).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
