belongsTo(ice11,struct2).
belongsTo(ice15,struct4).
belongsTo(ice16,struct4).
belongsTo(ice21,struct4).
belongsTo(ice6,struct2).
belongsTo(pig0,struct1).
belongsTo(stone9,struct1).
belongsTo(unknown24,struct8).
belongsTo(unknown25,struct8).
belongsTo(wood0,struct0).
belongsTo(wood1,struct1).
belongsTo(wood10,struct1).
belongsTo(wood12,struct1).
belongsTo(wood13,struct1).
belongsTo(wood14,struct3).
belongsTo(wood17,struct5).
belongsTo(wood18,struct6).
belongsTo(wood19,struct7).
belongsTo(wood2,struct1).
belongsTo(wood20,struct7).
belongsTo(wood22,struct8).
belongsTo(wood23,struct9).
belongsTo(wood26,struct8).
belongsTo(wood27,struct10).
belongsTo(wood28,struct8).
belongsTo(wood29,struct11).
belongsTo(wood3,struct1).
belongsTo(wood30,struct12).
belongsTo(wood4,struct2).
belongsTo(wood5,struct2).
belongsTo(wood7,struct1).
belongsTo(wood8,struct1).
bird(redbird0).
bird(redbird1).
bird(redbird2).
birdOrder(redbird0,2).
birdOrder(redbird1,1).
birdOrder(redbird2,0).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct10,struct9).
canCollapse(struct11,struct10).
canCollapse(struct11,struct12).
canCollapse(struct12,struct11).
canCollapse(struct2,struct1).
canCollapse(struct3,struct2).
canCollapse(struct4,struct3).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canCollapse(struct8,struct7).
canCollapse(struct8,struct9).
canCollapse(struct9,struct8).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(redbird0,red).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasForm(ice11,bar).
hasForm(ice15,block).
hasForm(ice16,bar).
hasForm(ice21,bar).
hasForm(ice6,bar).
hasForm(stone9,block).
hasForm(wood0,bar).
hasForm(wood1,bar).
hasForm(wood10,bar).
hasForm(wood12,bar).
hasForm(wood13,bar).
hasForm(wood14,bar).
hasForm(wood17,bar).
hasForm(wood18,bar).
hasForm(wood19,bar).
hasForm(wood2,bar).
hasForm(wood20,bar).
hasForm(wood22,bar).
hasForm(wood23,bar).
hasForm(wood26,block).
hasForm(wood27,block).
hasForm(wood28,cube).
hasForm(wood29,bar).
hasForm(wood3,bar).
hasForm(wood30,bar).
hasForm(wood4,bar).
hasForm(wood5,bar).
hasForm(wood7,bar).
hasForm(wood8,block).
hasMaterial(ice11,glass).
hasMaterial(ice15,glass).
hasMaterial(ice16,glass).
hasMaterial(ice21,glass).
hasMaterial(ice6,glass).
hasMaterial(stone9,stone).
hasMaterial(wood0,wood).
hasMaterial(wood1,wood).
hasMaterial(wood10,wood).
hasMaterial(wood12,wood).
hasMaterial(wood13,wood).
hasMaterial(wood14,wood).
hasMaterial(wood17,wood).
hasMaterial(wood18,wood).
hasMaterial(wood19,wood).
hasMaterial(wood2,wood).
hasMaterial(wood20,wood).
hasMaterial(wood22,wood).
hasMaterial(wood23,wood).
hasMaterial(wood26,wood).
hasMaterial(wood27,wood).
hasMaterial(wood28,wood).
hasMaterial(wood29,wood).
hasMaterial(wood3,wood).
hasMaterial(wood30,wood).
hasMaterial(wood4,wood).
hasMaterial(wood5,wood).
hasMaterial(wood7,wood).
hasMaterial(wood8,wood).
hasOrientation(ice11,vertical).
hasOrientation(ice15,horizontal).
hasOrientation(ice16,horizontal).
hasOrientation(ice21,horizontal).
hasOrientation(ice6,vertical).
hasOrientation(stone9,vertical).
hasOrientation(wood0,vertical).
hasOrientation(wood1,vertical).
hasOrientation(wood10,vertical).
hasOrientation(wood12,vertical).
hasOrientation(wood13,vertical).
hasOrientation(wood14,vertical).
hasOrientation(wood17,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood19,horizontal).
hasOrientation(wood2,horizontal).
hasOrientation(wood20,horizontal).
hasOrientation(wood22,horizontal).
hasOrientation(wood23,horizontal).
hasOrientation(wood26,vertical).
hasOrientation(wood27,horizontal).
hasOrientation(wood28,horizontal).
hasOrientation(wood29,horizontal).
hasOrientation(wood3,vertical).
hasOrientation(wood30,horizontal).
hasOrientation(wood4,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood7,horizontal).
hasOrientation(wood8,horizontal).
hasSize(ice11,medium).
hasSize(ice15,medium).
hasSize(ice16,big).
hasSize(ice21,big).
hasSize(ice6,medium).
hasSize(pig0,small).
hasSize(stone9,medium).
hasSize(unknown24,medium).
hasSize(unknown25,big).
hasSize(wood0,small).
hasSize(wood1,big).
hasSize(wood10,small).
hasSize(wood12,big).
hasSize(wood13,big).
hasSize(wood14,small).
hasSize(wood17,big).
hasSize(wood18,big).
hasSize(wood19,medium).
hasSize(wood2,big).
hasSize(wood20,small).
hasSize(wood22,big).
hasSize(wood23,big).
hasSize(wood26,medium).
hasSize(wood27,medium).
hasSize(wood28,small).
hasSize(wood29,big).
hasSize(wood3,big).
hasSize(wood30,big).
hasSize(wood4,big).
hasSize(wood5,medium).
hasSize(wood7,medium).
hasSize(wood8,medium).
isBelow(ice11,wood5).
isBelow(ice6,wood5).
isBelow(stone9,wood10).
isBelow(unknown24,wood22).
isBelow(unknown24,wood28).
isBelow(unknown25,unknown24).
isBelow(wood1,wood2).
isBelow(wood12,wood7).
isBelow(wood13,wood2).
isBelow(wood2,wood12).
isBelow(wood2,wood3).
isBelow(wood2,wood8).
isBelow(wood28,wood26).
isBelow(wood3,wood7).
isBelow(wood4,ice11).
isBelow(wood4,ice6).
isBelow(wood7,stone9).
isBelow(wood8,pig0).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(ice11,true).
isHittable(ice15,true).
isHittable(ice16,true).
isHittable(ice6,true).
isHittable(pig0,true).
isHittable(stone9,true).
isHittable(unknown24,true).
isHittable(unknown25,true).
isHittable(wood0,true).
isHittable(wood1,true).
isHittable(wood10,true).
isHittable(wood14,true).
isHittable(wood17,true).
isHittable(wood18,true).
isHittable(wood19,true).
isHittable(wood2,true).
isHittable(wood20,true).
isHittable(wood22,true).
isHittable(wood23,true).
isHittable(wood27,true).
isHittable(wood29,true).
isHittable(wood3,true).
isHittable(wood30,true).
isHittable(wood4,true).
isHittable(wood5,true).
isHittable(wood7,true).
isHittable(wood8,true).
isLeft(ice15,ice21).
isLeft(ice16,ice21).
isLeft(wood12,wood13).
isLeft(wood19,wood20).
isLeft(wood3,pig0).
isLeft(wood3,wood8).
isLeft(wood8,wood12).
isOn(ice11,wood4).
isOn(ice15,ground).
isOn(ice16,ground).
isOn(ice21,ground).
isOn(ice6,wood4).
isOn(pig0,wood8).
isOn(stone9,wood7).
isOn(unknown24,unknown25).
isOn(unknown25,ground).
isOn(wood0,ground).
isOn(wood1,ground).
isOn(wood10,stone9).
isOn(wood12,wood2).
isOn(wood13,ground).
isOn(wood14,ground).
isOn(wood17,ground).
isOn(wood18,ground).
isOn(wood19,ground).
isOn(wood2,wood1).
isOn(wood2,wood13).
isOn(wood20,ground).
isOn(wood22,unknown24).
isOn(wood23,ground).
isOn(wood26,wood28).
isOn(wood27,ground).
isOn(wood28,unknown24).
isOn(wood29,ground).
isOn(wood3,wood2).
isOn(wood30,ground).
isOn(wood4,ground).
isOn(wood5,ice11).
isOn(wood5,ice6).
isOn(wood7,wood12).
isOn(wood7,wood3).
isOn(wood8,wood2).
isOver(pig0,wood3).
isRight(ice21,ice15).
isRight(ice21,ice16).
isRight(pig0,wood3).
isRight(wood12,wood8).
isRight(wood13,wood12).
isRight(wood20,wood19).
isRight(wood8,wood3).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
object(unknown24).
object(unknown25).
pig(pig0).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(wood12,wood13).
supports(wood12,wood8).
supports(wood13,wood12).
supports(wood3,pig0).
supports(wood3,wood8).
