belongsTo(pig0,struct0).
belongsTo(pig1,struct0).
belongsTo(pig2,struct0).
belongsTo(unknown1,struct0).
belongsTo(unknown11,struct0).
belongsTo(unknown13,struct0).
belongsTo(unknown15,struct0).
belongsTo(unknown17,struct0).
belongsTo(unknown19,struct0).
belongsTo(unknown21,struct0).
belongsTo(unknown23,struct0).
belongsTo(unknown25,struct0).
belongsTo(unknown27,struct0).
belongsTo(unknown29,struct0).
belongsTo(unknown3,struct0).
belongsTo(unknown31,struct0).
belongsTo(unknown33,struct0).
belongsTo(unknown35,struct0).
belongsTo(unknown37,struct0).
belongsTo(unknown39,struct0).
belongsTo(unknown41,struct0).
belongsTo(unknown43,struct0).
belongsTo(unknown45,struct0).
belongsTo(unknown47,struct0).
belongsTo(unknown48,struct0).
belongsTo(unknown5,struct0).
belongsTo(unknown50,struct0).
belongsTo(unknown52,struct0).
belongsTo(unknown7,struct0).
belongsTo(unknown9,struct0).
bird(redbird3).
bird(redbird4).
bird(redbird5).
bird(redbird6).
birdOrder(redbird3,0).
birdOrder(redbird4,2).
birdOrder(redbird5,3).
birdOrder(redbird6,1).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasForm(unknown11,block).
hasForm(unknown13,block).
hasForm(unknown15,bar).
hasForm(unknown17,bar).
hasForm(unknown19,bar).
hasForm(unknown21,block).
hasForm(unknown23,block).
hasForm(unknown25,cube).
hasForm(unknown27,bar).
hasForm(unknown29,bar).
hasForm(unknown3,bar).
hasForm(unknown31,cube).
hasForm(unknown33,block).
hasForm(unknown35,bar).
hasForm(unknown37,bar).
hasForm(unknown39,bar).
hasForm(unknown41,block).
hasForm(unknown43,bar).
hasForm(unknown45,block).
hasForm(unknown47,bar).
hasForm(unknown48,block).
hasForm(unknown5,bar).
hasForm(unknown50,bar).
hasForm(unknown52,block).
hasForm(unknown7,block).
hasForm(unknown9,block).
hasMaterial(unknown11,glass).
hasMaterial(unknown13,glass).
hasMaterial(unknown15,glass).
hasMaterial(unknown17,wood).
hasMaterial(unknown19,glass).
hasMaterial(unknown21,glass).
hasMaterial(unknown23,glass).
hasMaterial(unknown25,glass).
hasMaterial(unknown27,stone).
hasMaterial(unknown29,glass).
hasMaterial(unknown3,stone).
hasMaterial(unknown31,glass).
hasMaterial(unknown33,glass).
hasMaterial(unknown35,wood).
hasMaterial(unknown37,stone).
hasMaterial(unknown39,glass).
hasMaterial(unknown41,glass).
hasMaterial(unknown43,glass).
hasMaterial(unknown45,glass).
hasMaterial(unknown47,wood).
hasMaterial(unknown48,glass).
hasMaterial(unknown5,wood).
hasMaterial(unknown50,stone).
hasMaterial(unknown52,wood).
hasMaterial(unknown7,glass).
hasMaterial(unknown9,wood).
hasOrientation(unknown11,horizontal).
hasOrientation(unknown13,vertical).
hasOrientation(unknown15,horizontal).
hasOrientation(unknown17,horizontal).
hasOrientation(unknown19,vertical).
hasOrientation(unknown21,vertical).
hasOrientation(unknown23,horizontal).
hasOrientation(unknown25,horizontal).
hasOrientation(unknown27,vertical).
hasOrientation(unknown29,horizontal).
hasOrientation(unknown3,vertical).
hasOrientation(unknown31,horizontal).
hasOrientation(unknown33,horizontal).
hasOrientation(unknown35,horizontal).
hasOrientation(unknown37,vertical).
hasOrientation(unknown39,vertical).
hasOrientation(unknown41,horizontal).
hasOrientation(unknown43,vertical).
hasOrientation(unknown45,horizontal).
hasOrientation(unknown47,horizontal).
hasOrientation(unknown48,vertical).
hasOrientation(unknown5,horizontal).
hasOrientation(unknown50,vertical).
hasOrientation(unknown52,horizontal).
hasOrientation(unknown7,vertical).
hasOrientation(unknown9,horizontal).
hill(unknown1).
isBelow(unknown1,unknown27).
isBelow(unknown1,unknown3).
isBelow(unknown1,unknown37).
isBelow(unknown1,unknown50).
isBelow(unknown11,unknown13).
isBelow(unknown11,unknown7).
isBelow(unknown13,unknown15).
isBelow(unknown15,unknown17).
isBelow(unknown15,unknown21).
isBelow(unknown15,unknown9).
isBelow(unknown17,pig0).
isBelow(unknown17,unknown21).
isBelow(unknown17,unknown29).
isBelow(unknown19,unknown15).
isBelow(unknown21,unknown23).
isBelow(unknown23,unknown25).
isBelow(unknown23,unknown33).
isBelow(unknown27,pig2).
isBelow(unknown27,unknown35).
isBelow(unknown27,unknown5).
isBelow(unknown29,unknown31).
isBelow(unknown29,unknown39).
isBelow(unknown3,unknown5).
isBelow(unknown31,unknown23).
isBelow(unknown35,pig2).
isBelow(unknown35,unknown43).
isBelow(unknown35,unknown45).
isBelow(unknown37,pig2).
isBelow(unknown37,unknown35).
isBelow(unknown37,unknown5).
isBelow(unknown39,unknown33).
isBelow(unknown41,unknown17).
isBelow(unknown41,unknown47).
isBelow(unknown41,unknown52).
isBelow(unknown43,unknown41).
isBelow(unknown45,unknown48).
isBelow(unknown47,pig1).
isBelow(unknown48,unknown17).
isBelow(unknown48,unknown47).
isBelow(unknown48,unknown52).
isBelow(unknown5,pig2).
isBelow(unknown5,unknown11).
isBelow(unknown5,unknown19).
isBelow(unknown50,unknown35).
isBelow(unknown50,unknown45).
isBelow(unknown52,pig1).
isBelow(unknown7,unknown17).
isBelow(unknown7,unknown9).
isBelow(unknown9,pig0).
isCollapsable(struct0).
isHittable(pig0,true).
isHittable(unknown1,true).
isHittable(unknown11,true).
isHittable(unknown13,true).
isHittable(unknown15,true).
isHittable(unknown17,true).
isHittable(unknown19,true).
isHittable(unknown21,true).
isHittable(unknown23,true).
isHittable(unknown25,true).
isHittable(unknown27,true).
isHittable(unknown3,true).
isHittable(unknown5,true).
isHittable(unknown7,true).
isHittable(unknown9,true).
isLeft(unknown11,unknown19).
isLeft(unknown13,unknown19).
isLeft(unknown17,unknown47).
isLeft(unknown19,pig2).
isLeft(unknown19,unknown27).
isLeft(unknown21,unknown29).
isLeft(unknown21,unknown31).
isLeft(unknown23,unknown39).
isLeft(unknown27,unknown37).
isLeft(unknown31,unknown39).
isLeft(unknown43,unknown45).
isLeft(unknown43,unknown48).
isLeft(unknown47,unknown52).
isLeft(unknown5,unknown35).
isLeft(unknown7,unknown13).
isLeft(unknown7,unknown15).
isLeft(unknown9,unknown17).
isOn(pig0,unknown17).
isOn(pig0,unknown17).
isOn(pig0,unknown9).
isOn(pig0,unknown9).
isOn(pig1,unknown47).
isOn(pig1,unknown52).
isOn(unknown11,unknown5).
isOn(unknown13,unknown11).
isOn(unknown15,unknown13).
isOn(unknown15,unknown19).
isOn(unknown17,unknown15).
isOn(unknown17,unknown41).
isOn(unknown17,unknown48).
isOn(unknown17,unknown7).
isOn(unknown19,unknown5).
isOn(unknown21,unknown15).
isOn(unknown21,unknown17).
isOn(unknown23,unknown21).
isOn(unknown23,unknown31).
isOn(unknown25,unknown23).
isOn(unknown27,unknown1).
isOn(unknown29,unknown17).
isOn(unknown3,unknown1).
isOn(unknown31,unknown29).
isOn(unknown33,unknown23).
isOn(unknown33,unknown39).
isOn(unknown35,unknown27).
isOn(unknown35,unknown37).
isOn(unknown35,unknown50).
isOn(unknown37,unknown1).
isOn(unknown39,unknown29).
isOn(unknown41,unknown43).
isOn(unknown43,unknown35).
isOn(unknown45,unknown35).
isOn(unknown45,unknown50).
isOn(unknown47,unknown41).
isOn(unknown47,unknown48).
isOn(unknown48,unknown45).
isOn(unknown5,unknown27).
isOn(unknown5,unknown3).
isOn(unknown5,unknown37).
isOn(unknown50,unknown1).
isOn(unknown52,unknown41).
isOn(unknown52,unknown48).
isOn(unknown7,unknown11).
isOn(unknown9,unknown15).
isOn(unknown9,unknown7).
isRight(unknown13,unknown7).
isRight(unknown15,unknown7).
isRight(unknown17,unknown9).
isRight(unknown19,unknown11).
isRight(unknown19,unknown13).
isRight(unknown27,unknown19).
isRight(unknown29,unknown21).
isRight(unknown31,unknown21).
isRight(unknown35,unknown5).
isRight(unknown37,unknown27).
isRight(unknown39,unknown23).
isRight(unknown39,unknown31).
isRight(unknown45,unknown43).
isRight(unknown47,unknown17).
isRight(unknown48,unknown43).
isRight(unknown52,unknown47).
onGround(redbird3).
onGround(redbird4).
onGround(redbird5).
onGround(redbird6).
onGround(unknown1).
pig(pig0).
pig(pig0).
pig(pig1).
structure(struct0).
supports(unknown11,unknown19).
supports(unknown13,unknown19).
supports(unknown13,unknown7).
supports(unknown15,unknown7).
supports(unknown19,unknown13).
supports(unknown19,unknown27).
supports(unknown23,unknown39).
supports(unknown27,unknown19).
supports(unknown27,unknown37).
supports(unknown29,unknown21).
supports(unknown31,unknown21).
supports(unknown31,unknown39).
supports(unknown37,unknown27).
supports(unknown43,unknown45).
supports(unknown45,unknown43).
supports(unknown48,unknown43).
supports(unknown7,unknown13).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
isDestroyable(X) :- object(X).
