belongsTo(ice17,struct1).
belongsTo(ice19,struct1).
belongsTo(ice27,struct1).
belongsTo(ice3,struct1).
belongsTo(ice5,struct1).
belongsTo(pig0,struct0).
belongsTo(stone11,struct1).
belongsTo(stone13,struct1).
belongsTo(stone23,struct1).
belongsTo(wood15,struct1).
belongsTo(wood21,struct1).
belongsTo(wood25,struct1).
belongsTo(wood7,struct1).
belongsTo(wood9,struct1).
bird(redbird1).
bird(redbird2).
bird(redbird3).
bird(redbird4).
birdOrder(redbird1,0).
birdOrder(redbird2,2).
birdOrder(redbird3,3).
birdOrder(redbird4,1).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasForm(ice17,bar).
hasForm(ice19,block).
hasForm(ice27,bar).
hasForm(ice3,bar).
hasForm(ice5,block).
hasForm(stone11,bar).
hasForm(stone13,bar).
hasForm(stone23,bar).
hasForm(wood15,bar).
hasForm(wood21,block).
hasForm(wood25,bar).
hasForm(wood7,block).
hasForm(wood9,bar).
hasMaterial(ice17,glass).
hasMaterial(ice19,glass).
hasMaterial(ice27,glass).
hasMaterial(ice3,glass).
hasMaterial(ice5,glass).
hasMaterial(stone11,stone).
hasMaterial(stone13,stone).
hasMaterial(stone23,stone).
hasMaterial(wood15,wood).
hasMaterial(wood21,wood).
hasMaterial(wood25,wood).
hasMaterial(wood7,wood).
hasMaterial(wood9,wood).
hasOrientation(ice17,vertical).
hasOrientation(ice19,horizontal).
hasOrientation(ice27,vertical).
hasOrientation(ice3,vertical).
hasOrientation(ice5,horizontal).
hasOrientation(stone11,vertical).
hasOrientation(stone13,horizontal).
hasOrientation(stone23,vertical).
hasOrientation(wood15,horizontal).
hasOrientation(wood21,horizontal).
hasOrientation(wood25,vertical).
hasOrientation(wood7,horizontal).
hasOrientation(wood9,vertical).
hasSize(ice17,big).
hasSize(ice19,medium).
hasSize(ice27,big).
hasSize(ice3,big).
hasSize(ice5,medium).
hasSize(pig0,medium).
hasSize(stone11,medium).
hasSize(stone13,big).
hasSize(stone23,medium).
hasSize(wood15,medium).
hasSize(wood21,medium).
hasSize(wood25,medium).
hasSize(wood7,medium).
hasSize(wood9,medium).
hill(hill1).
isAnchorPointFor(ice3,struct1).
isAnchorPointFor(pig0,struct0).
isBelow(ice27,ice19).
isBelow(ice3,ice5).
isBelow(stone11,stone13).
isBelow(stone11,wood7).
isBelow(stone13,wood15).
isBelow(stone23,stone13).
isBelow(stone23,wood21).
isBelow(wood15,ice17).
isBelow(wood25,wood21).
isBelow(wood9,wood7).
isCollapsable(struct0).
isCollapsable(struct1).
isHittable(ice19,true).
isHittable(ice3,true).
isHittable(ice5,true).
isHittable(stone13,true).
isLeft(ice17,ice19).
isLeft(ice3,wood7).
isLeft(ice3,wood9).
isLeft(ice5,ice17).
isLeft(ice5,ice19).
isLeft(wood15,wood21).
isLeft(wood21,ice27).
isLeft(wood25,ice27).
isLeft(wood7,wood15).
isOn(ice17,wood15).
isOn(ice19,ice27).
isOn(ice27,hill1).
isOn(ice3,hill1).
isOn(ice5,ice3).
isOn(pig0,hill1).
isOn(stone11,hill1).
isOn(stone13,stone11).
isOn(stone13,stone23).
isOn(stone23,hill1).
isOn(wood15,stone13).
isOn(wood21,stone23).
isOn(wood21,wood25).
isOn(wood25,hill1).
isOn(wood7,stone11).
isOn(wood7,wood9).
isOn(wood9,hill1).
isOver(pig0,stone13).
isRight(ice17,ice5).
isRight(ice19,ice17).
isRight(ice19,ice5).
isRight(ice27,wood21).
isRight(ice27,wood25).
isRight(wood15,wood7).
isRight(wood21,wood15).
isRight(wood7,ice3).
isRight(wood9,ice3).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
protects(struct1,pig0).
structure(struct0).
structure(struct1).
supports(ice17,ice19).
supports(ice17,ice5).
supports(ice19,ice17).
supports(ice19,ice5).
supports(ice27,wood21).
supports(ice27,wood25).
supports(ice3,wood7).
supports(ice3,wood9).
supports(ice5,ice17).
supports(ice5,ice19).
supports(wood21,ice27).
supports(wood21,wood15).
supports(wood25,ice27).
supports(wood7,ice3).
supports(wood7,wood15).
supports(wood9,ice3).
