belongsTo(ice11,struct0).
belongsTo(ice15,struct1).
belongsTo(ice21,struct5).
belongsTo(ice23,struct6).
belongsTo(ice25,struct7).
belongsTo(ice27,struct7).
belongsTo(ice29,struct7).
belongsTo(ice33,struct8).
belongsTo(ice35,struct9).
belongsTo(ice41,struct12).
belongsTo(ice43,struct11).
belongsTo(ice45,struct13).
belongsTo(ice47,struct13).
belongsTo(ice49,struct13).
belongsTo(ice53,struct14).
belongsTo(ice59,struct16).
belongsTo(ice61,struct17).
belongsTo(ice62,struct18).
belongsTo(ice64,struct18).
belongsTo(ice68,struct19).
belongsTo(ice8,struct0).
belongsTo(ice9,struct0).
belongsTo(pig0,struct2).
belongsTo(pig1,struct9).
belongsTo(pig2,struct15).
belongsTo(pig3,struct20).
belongsTo(stone13,struct1).
belongsTo(stone17,struct3).
belongsTo(stone19,struct4).
belongsTo(stone31,struct8).
belongsTo(stone37,struct10).
belongsTo(stone39,struct11).
belongsTo(stone51,struct14).
belongsTo(stone55,struct16).
belongsTo(stone57,struct17).
belongsTo(stone66,struct19).
bird(bluebird5).
bird(redbird4).
birdOrder(bluebird5,1).
birdOrder(redbird4,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct10,struct11).
canCollapse(struct11,struct10).
canCollapse(struct11,struct12).
canCollapse(struct12,struct11).
canCollapse(struct12,struct13).
canCollapse(struct13,struct14).
canCollapse(struct14,struct13).
canCollapse(struct14,struct15).
canCollapse(struct15,struct16).
canCollapse(struct16,struct15).
canCollapse(struct16,struct17).
canCollapse(struct17,struct16).
canCollapse(struct17,struct18).
canCollapse(struct18,struct19).
canCollapse(struct19,struct18).
canCollapse(struct19,struct20).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct3).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct8).
canCollapse(struct8,struct7).
canCollapse(struct8,struct9).
canCollapse(struct9,struct10).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct11,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct12,struct13,away).
collapsesInDirection(struct13,struct12,towards).
collapsesInDirection(struct13,struct14,away).
collapsesInDirection(struct14,struct13,towards).
collapsesInDirection(struct14,struct15,away).
collapsesInDirection(struct15,struct14,towards).
collapsesInDirection(struct15,struct16,away).
collapsesInDirection(struct16,struct15,towards).
collapsesInDirection(struct16,struct17,away).
collapsesInDirection(struct17,struct16,towards).
collapsesInDirection(struct17,struct18,away).
collapsesInDirection(struct18,struct17,towards).
collapsesInDirection(struct18,struct19,away).
collapsesInDirection(struct19,struct18,towards).
collapsesInDirection(struct19,struct20,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct20,struct19,towards).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct10,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(bluebird5,blue).
hasColor(redbird4,red).
hasForm(ice11,ball).
hasForm(ice15,block).
hasForm(ice21,block).
hasForm(ice23,cube).
hasForm(ice25,cube).
hasForm(ice27,cube).
hasForm(ice29,cube).
hasForm(ice33,block).
hasForm(ice35,cube).
hasForm(ice41,cube).
hasForm(ice43,block).
hasForm(ice45,ball).
hasForm(ice47,block).
hasForm(ice49,cube).
hasForm(ice53,cube).
hasForm(ice59,cube).
hasForm(ice61,block).
hasForm(ice62,block).
hasForm(ice64,cube).
hasForm(ice68,block).
hasForm(ice8,block).
hasForm(ice9,cube).
hasForm(stone13,block).
hasForm(stone17,ball).
hasForm(stone19,ball).
hasForm(stone31,block).
hasForm(stone37,ball).
hasForm(stone39,block).
hasForm(stone51,ball).
hasForm(stone55,ball).
hasForm(stone57,block).
hasForm(stone66,ball).
hasMaterial(ice11,glass).
hasMaterial(ice15,glass).
hasMaterial(ice21,glass).
hasMaterial(ice23,glass).
hasMaterial(ice25,glass).
hasMaterial(ice27,glass).
hasMaterial(ice29,glass).
hasMaterial(ice33,glass).
hasMaterial(ice35,glass).
hasMaterial(ice41,glass).
hasMaterial(ice43,glass).
hasMaterial(ice45,glass).
hasMaterial(ice47,glass).
hasMaterial(ice49,glass).
hasMaterial(ice53,glass).
hasMaterial(ice59,glass).
hasMaterial(ice61,glass).
hasMaterial(ice62,glass).
hasMaterial(ice64,glass).
hasMaterial(ice68,glass).
hasMaterial(ice8,glass).
hasMaterial(ice9,glass).
hasMaterial(stone13,stone).
hasMaterial(stone17,stone).
hasMaterial(stone19,stone).
hasMaterial(stone31,stone).
hasMaterial(stone37,stone).
hasMaterial(stone39,stone).
hasMaterial(stone51,stone).
hasMaterial(stone55,stone).
hasMaterial(stone57,stone).
hasMaterial(stone66,stone).
hasOrientation(ice11,horizontal).
hasOrientation(ice15,vertical).
hasOrientation(ice21,horizontal).
hasOrientation(ice23,horizontal).
hasOrientation(ice25,horizontal).
hasOrientation(ice27,horizontal).
hasOrientation(ice29,horizontal).
hasOrientation(ice33,vertical).
hasOrientation(ice35,horizontal).
hasOrientation(ice41,horizontal).
hasOrientation(ice43,vertical).
hasOrientation(ice45,horizontal).
hasOrientation(ice47,vertical).
hasOrientation(ice49,horizontal).
hasOrientation(ice53,horizontal).
hasOrientation(ice59,horizontal).
hasOrientation(ice61,vertical).
hasOrientation(ice62,horizontal).
hasOrientation(ice64,horizontal).
hasOrientation(ice68,vertical).
hasOrientation(ice8,vertical).
hasOrientation(ice9,horizontal).
hasOrientation(stone13,horizontal).
hasOrientation(stone17,horizontal).
hasOrientation(stone19,horizontal).
hasOrientation(stone31,horizontal).
hasOrientation(stone37,horizontal).
hasOrientation(stone39,horizontal).
hasOrientation(stone51,horizontal).
hasOrientation(stone55,horizontal).
hasOrientation(stone57,horizontal).
hasOrientation(stone66,horizontal).
hasSize(ice11,medium).
hasSize(ice15,medium).
hasSize(ice21,medium).
hasSize(ice23,small).
hasSize(ice25,small).
hasSize(ice27,small).
hasSize(ice29,small).
hasSize(ice33,medium).
hasSize(ice35,small).
hasSize(ice41,small).
hasSize(ice43,medium).
hasSize(ice45,medium).
hasSize(ice47,medium).
hasSize(ice49,small).
hasSize(ice53,small).
hasSize(ice59,small).
hasSize(ice61,medium).
hasSize(ice62,medium).
hasSize(ice64,small).
hasSize(ice68,medium).
hasSize(ice8,medium).
hasSize(ice9,small).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(stone13,medium).
hasSize(stone17,medium).
hasSize(stone19,medium).
hasSize(stone31,medium).
hasSize(stone37,medium).
hasSize(stone39,medium).
hasSize(stone51,medium).
hasSize(stone55,medium).
hasSize(stone57,medium).
hasSize(stone66,medium).
hill(hill2).
hill(hill3).
hill(hill4).
hill(hill5).
hill(hill6).
isAnchorPointFor(ice21,struct5).
isAnchorPointFor(ice23,struct6).
isAnchorPointFor(ice25,struct7).
isAnchorPointFor(ice41,struct12).
isAnchorPointFor(ice45,struct13).
isAnchorPointFor(ice62,struct18).
isAnchorPointFor(ice8,struct0).
isAnchorPointFor(pig0,struct2).
isAnchorPointFor(pig1,struct9).
isAnchorPointFor(pig2,struct15).
isAnchorPointFor(pig3,struct20).
isAnchorPointFor(stone13,struct1).
isAnchorPointFor(stone17,struct3).
isAnchorPointFor(stone19,struct4).
isAnchorPointFor(stone31,struct8).
isAnchorPointFor(stone37,struct10).
isAnchorPointFor(stone39,struct11).
isAnchorPointFor(stone51,struct14).
isAnchorPointFor(stone55,struct16).
isAnchorPointFor(stone57,struct17).
isAnchorPointFor(stone66,struct19).
isBelow(ice15,stone13).
isBelow(ice33,stone31).
isBelow(ice35,pig1).
isBelow(ice43,stone39).
isBelow(ice45,ice47).
isBelow(ice53,stone51).
isBelow(ice59,stone55).
isBelow(ice61,stone57).
isBelow(ice68,stone66).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct13).
isCollapsable(struct14).
isCollapsable(struct15).
isCollapsable(struct16).
isCollapsable(struct17).
isCollapsable(struct18).
isCollapsable(struct19).
isCollapsable(struct2).
isCollapsable(struct20).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(ice11,true).
isHittable(ice15,true).
isHittable(ice23,true).
isHittable(ice25,true).
isHittable(ice27,true).
isHittable(ice29,true).
isHittable(ice41,true).
isHittable(ice45,true).
isHittable(ice47,true).
isHittable(ice53,true).
isHittable(ice59,true).
isHittable(ice61,true).
isHittable(ice62,true).
isHittable(ice64,true).
isHittable(ice68,true).
isHittable(ice8,true).
isHittable(ice9,true).
isHittable(pig0,true).
isHittable(pig3,true).
isHittable(stone13,true).
isHittable(stone19,true).
isHittable(stone31,true).
isHittable(stone37,true).
isHittable(stone39,true).
isHittable(stone51,true).
isHittable(stone55,true).
isHittable(stone57,true).
isLeft(ice25,ice27).
isLeft(ice27,ice29).
isLeft(ice45,ice49).
isLeft(ice62,ice64).
isLeft(ice8,ice9).
isLeft(ice9,ice11).
isOn(ice11,ground).
isOn(ice15,ground).
isOn(ice21,ground).
isOn(ice23,ground).
isOn(ice25,ground).
isOn(ice27,ground).
isOn(ice29,ground).
isOn(ice33,ground).
isOn(ice35,ground).
isOn(ice41,ground).
isOn(ice43,ground).
isOn(ice45,ground).
isOn(ice47,ice45).
isOn(ice49,ground).
isOn(ice53,ground).
isOn(ice59,ground).
isOn(ice61,ground).
isOn(ice62,ground).
isOn(ice64,ground).
isOn(ice68,ground).
isOn(ice8,ground).
isOn(ice9,ground).
isOn(pig0,ground).
isOn(pig1,ice35).
isOn(pig2,ground).
isOn(pig3,ground).
isOn(stone13,ice15).
isOn(stone17,ground).
isOn(stone19,ground).
isOn(stone31,ice33).
isOn(stone37,ground).
isOn(stone39,ice43).
isOn(stone51,ice53).
isOn(stone55,ice59).
isOn(stone57,ice61).
isOn(stone66,ice68).
isOver(pig1,stone31).
isOver(stone17,ice23).
isOver(stone37,ice43).
isOver(stone55,ice61).
isRight(ice11,ice9).
isRight(ice27,ice25).
isRight(ice29,ice27).
isRight(ice49,ice45).
isRight(ice64,ice62).
isRight(ice9,ice8).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
protects(struct8,pig1).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct13).
structure(struct14).
structure(struct15).
structure(struct16).
structure(struct17).
structure(struct18).
structure(struct19).
structure(struct2).
structure(struct20).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(ice25,ice27).
supports(ice27,ice25).
supports(ice27,ice29).
supports(ice29,ice27).
supports(ice49,ice45).
supports(ice64,ice62).
supports(ice8,ice9).
