belongsTo(pig0,struct5).
belongsTo(pig1,struct8).
belongsTo(pig2,struct1).
belongsTo(pig3,struct2).
belongsTo(pig4,struct10).
belongsTo(stone11,struct3).
belongsTo(stone13,struct3).
belongsTo(stone15,struct3).
belongsTo(stone17,struct3).
belongsTo(stone19,struct3).
belongsTo(stone21,struct3).
belongsTo(stone23,struct3).
belongsTo(stone25,struct6).
belongsTo(stone27,struct6).
belongsTo(stone29,struct6).
belongsTo(stone31,struct6).
belongsTo(stone33,struct6).
belongsTo(stone39,struct6).
belongsTo(stone41,struct6).
belongsTo(stone43,struct4).
belongsTo(stone45,struct6).
belongsTo(stone46,struct5).
belongsTo(stone48,struct6).
belongsTo(stone50,struct6).
belongsTo(stone52,struct6).
belongsTo(stone54,struct6).
belongsTo(stone56,struct6).
belongsTo(stone58,struct6).
belongsTo(stone59,struct7).
belongsTo(stone61,struct9).
belongsTo(stone63,struct9).
belongsTo(stone65,struct9).
belongsTo(stone67,struct9).
belongsTo(stone69,struct9).
belongsTo(stone71,struct9).
belongsTo(stone73,struct9).
belongsTo(stone74,struct10).
belongsTo(stone8,struct1).
belongsTo(stone9,struct2).
belongsTo(tnt81,struct4).
belongsTo(wood35,struct4).
belongsTo(wood37,struct5).
belongsTo(wood7,struct0).
belongsTo(wood78,struct11).
belongsTo(wood80,struct12).
bird(whitebird5).
bird(whitebird6).
bird(whitebird7).
bird(whitebird8).
bird(whitebird9).
birdOrder(whitebird5,0).
birdOrder(whitebird6,4).
birdOrder(whitebird7,3).
birdOrder(whitebird8,2).
birdOrder(whitebird9,1).
canCollapse(struct1,struct2).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct8).
canCollapse(struct8,struct7).
canCollapse(struct8,struct9).
canCollapse(struct9,struct10).
canCollapse(struct9,struct8).
canExplode(tnt81,pig2).
canExplode(tnt81,pig3).
canExplode(tnt81,stone11).
canExplode(tnt81,stone13).
canExplode(tnt81,stone15).
canExplode(tnt81,stone17).
canExplode(tnt81,stone19).
canExplode(tnt81,stone21).
canExplode(tnt81,stone23).
canExplode(tnt81,stone25).
canExplode(tnt81,stone27).
canExplode(tnt81,stone29).
canExplode(tnt81,stone31).
canExplode(tnt81,stone33).
canExplode(tnt81,stone41).
canExplode(tnt81,stone43).
canExplode(tnt81,stone8).
canExplode(tnt81,stone9).
canExplode(tnt81,wood35).
canExplode(tnt81,wood7).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct11,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct10,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(whitebird5,white).
hasColor(whitebird6,white).
hasColor(whitebird7,white).
hasColor(whitebird8,white).
hasColor(whitebird9,white).
hasForm(stone11,block).
hasForm(stone13,cube).
hasForm(stone15,block).
hasForm(stone17,cube).
hasForm(stone19,block).
hasForm(stone21,cube).
hasForm(stone23,block).
hasForm(stone25,cube).
hasForm(stone27,bar).
hasForm(stone29,block).
hasForm(stone31,block).
hasForm(stone33,block).
hasForm(stone39,bar).
hasForm(stone41,block).
hasForm(stone43,cube).
hasForm(stone45,block).
hasForm(stone46,block).
hasForm(stone48,block).
hasForm(stone50,block).
hasForm(stone52,block).
hasForm(stone54,bar).
hasForm(stone56,cube).
hasForm(stone58,block).
hasForm(stone59,block).
hasForm(stone61,block).
hasForm(stone63,block).
hasForm(stone65,block).
hasForm(stone67,cube).
hasForm(stone69,block).
hasForm(stone71,block).
hasForm(stone73,block).
hasForm(stone74,block).
hasForm(stone8,block).
hasForm(stone9,block).
hasForm(wood35,block).
hasForm(wood37,bar).
hasForm(wood7,cube).
hasForm(wood78,block).
hasForm(wood80,block).
hasMaterial(stone11,stone).
hasMaterial(stone13,stone).
hasMaterial(stone15,stone).
hasMaterial(stone17,stone).
hasMaterial(stone19,stone).
hasMaterial(stone21,stone).
hasMaterial(stone23,stone).
hasMaterial(stone25,stone).
hasMaterial(stone27,stone).
hasMaterial(stone29,stone).
hasMaterial(stone31,stone).
hasMaterial(stone33,stone).
hasMaterial(stone39,stone).
hasMaterial(stone41,stone).
hasMaterial(stone43,stone).
hasMaterial(stone45,stone).
hasMaterial(stone46,stone).
hasMaterial(stone48,stone).
hasMaterial(stone50,stone).
hasMaterial(stone52,stone).
hasMaterial(stone54,stone).
hasMaterial(stone56,stone).
hasMaterial(stone58,stone).
hasMaterial(stone59,stone).
hasMaterial(stone61,stone).
hasMaterial(stone63,stone).
hasMaterial(stone65,stone).
hasMaterial(stone67,stone).
hasMaterial(stone69,stone).
hasMaterial(stone71,stone).
hasMaterial(stone73,stone).
hasMaterial(stone74,stone).
hasMaterial(stone8,stone).
hasMaterial(stone9,stone).
hasMaterial(tnt81,tnt).
hasMaterial(wood35,wood).
hasMaterial(wood37,wood).
hasMaterial(wood7,wood).
hasMaterial(wood78,wood).
hasMaterial(wood80,wood).
hasOrientation(stone11,vertical).
hasOrientation(stone13,horizontal).
hasOrientation(stone15,horizontal).
hasOrientation(stone17,horizontal).
hasOrientation(stone19,horizontal).
hasOrientation(stone21,horizontal).
hasOrientation(stone23,vertical).
hasOrientation(stone25,horizontal).
hasOrientation(stone27,horizontal).
hasOrientation(stone29,horizontal).
hasOrientation(stone31,vertical).
hasOrientation(stone33,vertical).
hasOrientation(stone39,horizontal).
hasOrientation(stone41,vertical).
hasOrientation(stone43,horizontal).
hasOrientation(stone45,vertical).
hasOrientation(stone46,horizontal).
hasOrientation(stone48,vertical).
hasOrientation(stone50,horizontal).
hasOrientation(stone52,vertical).
hasOrientation(stone54,horizontal).
hasOrientation(stone56,horizontal).
hasOrientation(stone58,vertical).
hasOrientation(stone59,horizontal).
hasOrientation(stone61,horizontal).
hasOrientation(stone63,vertical).
hasOrientation(stone65,horizontal).
hasOrientation(stone67,horizontal).
hasOrientation(stone69,vertical).
hasOrientation(stone71,vertical).
hasOrientation(stone73,vertical).
hasOrientation(stone74,horizontal).
hasOrientation(stone8,horizontal).
hasOrientation(stone9,horizontal).
hasOrientation(wood35,horizontal).
hasOrientation(wood37,horizontal).
hasOrientation(wood7,horizontal).
hasOrientation(wood78,vertical).
hasOrientation(wood80,horizontal).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(pig4,medium).
hasSize(stone11,medium).
hasSize(stone13,big).
hasSize(stone15,medium).
hasSize(stone17,big).
hasSize(stone19,medium).
hasSize(stone21,big).
hasSize(stone23,medium).
hasSize(stone25,big).
hasSize(stone27,big).
hasSize(stone29,medium).
hasSize(stone31,medium).
hasSize(stone33,medium).
hasSize(stone39,big).
hasSize(stone41,medium).
hasSize(stone43,big).
hasSize(stone45,medium).
hasSize(stone46,medium).
hasSize(stone48,medium).
hasSize(stone50,medium).
hasSize(stone52,medium).
hasSize(stone54,big).
hasSize(stone56,big).
hasSize(stone58,medium).
hasSize(stone59,medium).
hasSize(stone61,medium).
hasSize(stone63,medium).
hasSize(stone65,medium).
hasSize(stone67,big).
hasSize(stone69,medium).
hasSize(stone71,medium).
hasSize(stone73,medium).
hasSize(stone74,medium).
hasSize(stone8,medium).
hasSize(stone9,medium).
hasSize(tnt81,big).
hasSize(wood35,medium).
hasSize(wood37,big).
hasSize(wood7,big).
hasSize(wood78,medium).
hasSize(wood80,medium).
hill(hill2).
hill(hill3).
hill(hill4).
isAnchorPointFor(pig1,struct8).
isAnchorPointFor(stone11,struct3).
isAnchorPointFor(stone25,struct6).
isAnchorPointFor(stone59,struct7).
isAnchorPointFor(stone61,struct9).
isAnchorPointFor(stone74,struct10).
isAnchorPointFor(stone8,struct1).
isAnchorPointFor(stone9,struct2).
isAnchorPointFor(wood35,struct4).
isAnchorPointFor(wood37,struct5).
isAnchorPointFor(wood7,struct0).
isAnchorPointFor(wood78,struct11).
isAnchorPointFor(wood80,struct12).
isBelow(pig0,stone46).
isBelow(pig2,stone8).
isBelow(pig3,stone9).
isBelow(pig4,stone74).
isBelow(stone13,stone15).
isBelow(stone15,stone17).
isBelow(stone15,stone23).
isBelow(stone17,stone19).
isBelow(stone19,stone11).
isBelow(stone21,stone15).
isBelow(stone23,stone19).
isBelow(stone25,stone29).
isBelow(stone27,stone25).
isBelow(stone27,stone33).
isBelow(stone29,stone31).
isBelow(stone29,stone39).
isBelow(stone29,stone41).
isBelow(stone33,stone29).
isBelow(stone39,stone41).
isBelow(stone39,stone45).
isBelow(stone39,stone48).
isBelow(stone50,stone39).
isBelow(stone50,stone58).
isBelow(stone52,stone50).
isBelow(stone54,stone52).
isBelow(stone54,stone56).
isBelow(stone56,stone50).
isBelow(stone61,stone73).
isBelow(stone63,stone65).
isBelow(stone65,stone67).
isBelow(stone65,stone71).
isBelow(stone67,stone61).
isBelow(stone69,stone65).
isBelow(stone71,stone61).
isBelow(tnt81,stone43).
isBelow(wood37,pig0).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(pig0,true).
isHittable(pig2,true).
isHittable(pig3,true).
isHittable(stone11,true).
isHittable(stone13,true).
isHittable(stone15,true).
isHittable(stone19,true).
isHittable(stone25,true).
isHittable(stone27,true).
isHittable(stone29,true).
isHittable(stone31,true).
isHittable(stone39,true).
isHittable(stone41,true).
isHittable(stone43,true).
isHittable(stone45,true).
isHittable(stone48,true).
isHittable(stone52,true).
isHittable(stone54,true).
isHittable(stone58,true).
isHittable(stone8,true).
isHittable(stone9,true).
isHittable(wood7,true).
isHittable(wood78,true).
isHittable(wood80,true).
isLeft(stone13,stone21).
isLeft(stone17,stone23).
isLeft(stone25,stone33).
isLeft(stone48,stone50).
isLeft(stone52,stone56).
isLeft(stone63,stone69).
isLeft(stone67,stone71).
isLeft(wood35,tnt81).
isOn(pig0,wood37).
isOn(pig1,ground).
isOn(pig2,ground).
isOn(pig3,ground).
isOn(pig4,ground).
isOn(stone11,stone19).
isOn(stone13,hill2).
isOn(stone15,stone13).
isOn(stone15,stone21).
isOn(stone17,stone15).
isOn(stone19,stone17).
isOn(stone19,stone23).
isOn(stone21,hill2).
isOn(stone23,stone15).
isOn(stone25,stone27).
isOn(stone27,ground).
isOn(stone29,stone25).
isOn(stone29,stone33).
isOn(stone31,stone29).
isOn(stone33,stone27).
isOn(stone39,stone29).
isOn(stone39,stone50).
isOn(stone41,stone29).
isOn(stone41,stone39).
isOn(stone43,tnt81).
isOn(stone45,stone39).
isOn(stone46,pig0).
isOn(stone48,stone39).
isOn(stone50,stone52).
isOn(stone50,stone56).
isOn(stone52,stone54).
isOn(stone54,ground).
isOn(stone56,stone54).
isOn(stone58,stone50).
isOn(stone59,ground).
isOn(stone61,stone67).
isOn(stone61,stone71).
isOn(stone63,hill3).
isOn(stone65,stone63).
isOn(stone65,stone69).
isOn(stone67,stone65).
isOn(stone69,hill3).
isOn(stone71,stone65).
isOn(stone73,stone61).
isOn(stone74,pig4).
isOn(stone8,pig2).
isOn(stone9,pig3).
isOn(tnt81,ground).
isOn(wood35,ground).
isOn(wood37,hill2).
isOn(wood7,ground).
isOn(wood78,ground).
isOn(wood80,ground).
isOver(pig0,stone46).
isOver(pig1,stone59).
isOver(pig2,stone8).
isOver(pig3,stone9).
isOver(pig4,stone74).
isOver(tnt81,wood35).
isRight(stone21,stone13).
isRight(stone23,stone17).
isRight(stone33,stone25).
isRight(stone50,stone48).
isRight(stone56,stone52).
isRight(stone69,stone63).
isRight(stone71,stone67).
isRight(tnt81,wood35).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
pig(pig4).
protects(struct3,pig3).
protects(struct6,pig0).
protects(struct6,pig1).
protects(struct7,pig1).
protects(struct9,pig1).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(stone23,stone17).
supports(stone33,stone25).
supports(stone48,stone50).
supports(stone52,stone56).
supports(stone63,stone69).
supports(stone69,stone63).
supports(stone71,stone67).
