belongsTo(ice21,struct2).
belongsTo(ice33,struct2).
belongsTo(ice39,struct0).
belongsTo(pig0,struct0).
belongsTo(pig1,struct1).
belongsTo(pig2,struct3).
belongsTo(stone13,struct0).
belongsTo(stone15,struct0).
belongsTo(stone17,struct0).
belongsTo(stone19,struct0).
belongsTo(stone23,struct0).
belongsTo(stone27,struct0).
belongsTo(stone35,struct0).
belongsTo(stone41,struct0).
belongsTo(stone45,struct0).
belongsTo(stone47,struct0).
belongsTo(stone49,struct0).
belongsTo(wood11,struct0).
belongsTo(wood25,struct0).
belongsTo(wood29,struct0).
belongsTo(wood31,struct0).
belongsTo(wood37,struct0).
belongsTo(wood43,struct0).
belongsTo(wood5,struct0).
belongsTo(wood51,struct0).
belongsTo(wood53,struct0).
belongsTo(wood55,struct0).
belongsTo(wood7,struct0).
belongsTo(wood9,struct0).
bird(blackbird5).
bird(bluebird4).
bird(yellowbird3).
birdOrder(blackbird5,1).
birdOrder(bluebird4,2).
birdOrder(yellowbird3,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct2,struct1).
canCollapse(struct2,struct3).
canCollapse(struct3,struct2).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
hasColor(blackbird5,black).
hasColor(bluebird4,blue).
hasColor(yellowbird3,yellow).
hasForm(ice21,block).
hasForm(ice33,cube).
hasForm(ice39,cube).
hasForm(stone13,cube).
hasForm(stone15,block).
hasForm(stone17,block).
hasForm(stone19,bar).
hasForm(stone23,block).
hasForm(stone27,bar).
hasForm(stone35,bar).
hasForm(stone41,block).
hasForm(stone45,block).
hasForm(stone47,block).
hasForm(stone49,block).
hasForm(wood11,cube).
hasForm(wood25,bar).
hasForm(wood29,block).
hasForm(wood31,block).
hasForm(wood37,cube).
hasForm(wood43,bar).
hasForm(wood5,bar).
hasForm(wood51,block).
hasForm(wood53,block).
hasForm(wood55,block).
hasForm(wood7,block).
hasForm(wood9,cube).
hasMaterial(ice21,glass).
hasMaterial(ice33,glass).
hasMaterial(ice39,glass).
hasMaterial(stone13,stone).
hasMaterial(stone15,stone).
hasMaterial(stone17,stone).
hasMaterial(stone19,stone).
hasMaterial(stone23,stone).
hasMaterial(stone27,stone).
hasMaterial(stone35,stone).
hasMaterial(stone41,stone).
hasMaterial(stone45,stone).
hasMaterial(stone47,stone).
hasMaterial(stone49,stone).
hasMaterial(wood11,wood).
hasMaterial(wood25,wood).
hasMaterial(wood29,wood).
hasMaterial(wood31,wood).
hasMaterial(wood37,wood).
hasMaterial(wood43,wood).
hasMaterial(wood5,wood).
hasMaterial(wood51,wood).
hasMaterial(wood53,wood).
hasMaterial(wood55,wood).
hasMaterial(wood7,wood).
hasMaterial(wood9,wood).
hasOrientation(ice21,horizontal).
hasOrientation(ice33,horizontal).
hasOrientation(ice39,horizontal).
hasOrientation(stone13,horizontal).
hasOrientation(stone15,vertical).
hasOrientation(stone17,vertical).
hasOrientation(stone19,horizontal).
hasOrientation(stone23,vertical).
hasOrientation(stone27,horizontal).
hasOrientation(stone35,horizontal).
hasOrientation(stone41,horizontal).
hasOrientation(stone45,vertical).
hasOrientation(stone47,vertical).
hasOrientation(stone49,vertical).
hasOrientation(wood11,horizontal).
hasOrientation(wood25,horizontal).
hasOrientation(wood29,vertical).
hasOrientation(wood31,horizontal).
hasOrientation(wood37,horizontal).
hasOrientation(wood43,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood51,vertical).
hasOrientation(wood53,vertical).
hasOrientation(wood55,vertical).
hasOrientation(wood7,vertical).
hasOrientation(wood9,horizontal).
hasSize(ice21,medium).
hasSize(ice33,big).
hasSize(ice39,big).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(stone13,big).
hasSize(stone15,medium).
hasSize(stone17,medium).
hasSize(stone19,big).
hasSize(stone23,medium).
hasSize(stone27,big).
hasSize(stone35,big).
hasSize(stone41,medium).
hasSize(stone45,medium).
hasSize(stone47,medium).
hasSize(stone49,medium).
hasSize(wood11,big).
hasSize(wood25,big).
hasSize(wood29,medium).
hasSize(wood31,medium).
hasSize(wood37,big).
hasSize(wood43,big).
hasSize(wood5,big).
hasSize(wood51,medium).
hasSize(wood53,medium).
hasSize(wood55,medium).
hasSize(wood7,medium).
hasSize(wood9,big).
hill(hill2).
hill(hill3).
isAnchorPointFor(ice21,struct2).
isAnchorPointFor(pig1,struct1).
isAnchorPointFor(pig2,struct3).
isAnchorPointFor(wood5,struct0).
isBelow(stone13,stone15).
isBelow(stone15,stone17).
isBelow(stone17,wood5).
isBelow(stone19,stone13).
isBelow(stone19,stone23).
isBelow(stone19,stone27).
isBelow(stone23,stone17).
isBelow(stone27,ice39).
isBelow(stone27,pig0).
isBelow(stone35,stone27).
isBelow(stone35,stone41).
isBelow(stone35,stone45).
isBelow(stone45,stone47).
isBelow(stone47,stone49).
isBelow(stone49,wood43).
isBelow(wood25,wood29).
isBelow(wood29,wood31).
isBelow(wood29,wood37).
isBelow(wood43,wood25).
isBelow(wood43,wood51).
isBelow(wood5,wood25).
isBelow(wood5,wood7).
isBelow(wood51,wood53).
isBelow(wood51,wood55).
isBelow(wood7,wood11).
isBelow(wood7,wood9).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isHittable(ice39,true).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(stone19,true).
isHittable(stone23,true).
isHittable(stone27,true).
isHittable(stone35,true).
isHittable(stone47,true).
isHittable(stone49,true).
isHittable(wood11,true).
isHittable(wood25,true).
isHittable(wood29,true).
isHittable(wood31,true).
isHittable(wood37,true).
isHittable(wood43,true).
isHittable(wood5,true).
isHittable(wood51,true).
isHittable(wood53,true).
isHittable(wood55,true).
isHittable(wood7,true).
isHittable(wood9,true).
isLeft(ice21,ice33).
isLeft(ice39,stone41).
isLeft(pig0,ice39).
isLeft(stone13,stone23).
isLeft(stone15,stone23).
isLeft(stone19,stone35).
isLeft(stone27,stone41).
isLeft(stone41,stone45).
isLeft(stone41,stone47).
isLeft(stone41,stone49).
isLeft(wood31,wood37).
isLeft(wood53,wood55).
isLeft(wood9,wood11).
isOn(ice21,hill2).
isOn(ice33,ground).
isOn(ice39,stone27).
isOn(pig0,stone27).
isOn(pig1,hill2).
isOn(pig2,ground).
isOn(stone13,stone19).
isOn(stone15,stone13).
isOn(stone17,stone15).
isOn(stone17,stone23).
isOn(stone19,hill2).
isOn(stone23,stone19).
isOn(stone27,stone19).
isOn(stone27,stone35).
isOn(stone35,hill3).
isOn(stone41,stone35).
isOn(stone45,stone35).
isOn(stone47,stone45).
isOn(stone49,stone47).
isOn(wood11,wood7).
isOn(wood25,wood43).
isOn(wood25,wood5).
isOn(wood29,wood25).
isOn(wood31,wood29).
isOn(wood37,wood29).
isOn(wood43,stone49).
isOn(wood5,stone17).
isOn(wood51,wood43).
isOn(wood53,wood51).
isOn(wood55,wood51).
isOn(wood7,wood5).
isOn(wood9,wood7).
isOver(pig0,wood25).
isOver(pig1,ice21).
isOver(pig2,ice33).
isRight(ice33,ice21).
isRight(ice39,pig0).
isRight(stone23,stone13).
isRight(stone23,stone15).
isRight(stone35,stone19).
isRight(stone41,ice39).
isRight(stone41,stone27).
isRight(stone45,stone41).
isRight(stone47,stone41).
isRight(stone49,stone41).
isRight(wood11,wood9).
isRight(wood37,wood31).
isRight(wood55,wood53).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
protects(struct0,pig1).
protects(struct0,pig2).
protects(struct2,pig1).
protects(struct2,pig2).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
supports(ice21,ice33).
supports(ice33,ice21).
supports(ice39,pig0).
supports(ice39,stone41).
supports(stone15,stone23).
supports(stone23,stone13).
supports(stone23,stone15).
supports(stone41,ice39).
supports(stone41,stone27).
supports(stone41,stone45).
supports(stone41,stone47).
supports(stone41,stone49).
supports(stone45,stone41).
supports(stone47,stone41).
supports(stone49,stone41).
supports(wood11,wood9).
supports(wood31,wood37).
supports(wood37,wood31).
supports(wood53,wood55).
supports(wood55,wood53).
supports(wood9,wood11).
