belongsTo(ice10,struct0).
belongsTo(ice12,struct0).
belongsTo(ice18,struct0).
belongsTo(ice24,struct0).
belongsTo(ice26,struct0).
belongsTo(ice30,struct0).
belongsTo(ice34,struct3).
belongsTo(ice36,struct4).
belongsTo(ice8,struct0).
belongsTo(pig0,struct0).
belongsTo(pig1,struct1).
belongsTo(pig2,struct2).
belongsTo(pig3,struct2).
belongsTo(stone38,struct5).
belongsTo(stone40,struct3).
belongsTo(stone42,struct3).
belongsTo(stone44,struct3).
belongsTo(wood14,struct0).
belongsTo(wood16,struct0).
belongsTo(wood20,struct0).
belongsTo(wood22,struct0).
belongsTo(wood28,struct0).
belongsTo(wood32,struct0).
belongsTo(wood4,struct0).
belongsTo(wood6,struct0).
bird(bluebird5).
bird(bluebird6).
bird(redbird4).
birdOrder(bluebird5,2).
birdOrder(bluebird6,0).
birdOrder(redbird4,1).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct3,struct4).
canCollapse(struct4,struct3).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
hasColor(bluebird5,blue).
hasColor(bluebird6,blue).
hasColor(redbird4,red).
hasForm(ice10,cube).
hasForm(ice12,block).
hasForm(ice18,block).
hasForm(ice24,cube).
hasForm(ice26,block).
hasForm(ice30,block).
hasForm(ice34,bar).
hasForm(ice36,block).
hasForm(ice8,block).
hasForm(stone38,ball).
hasForm(stone40,ball).
hasForm(stone42,ball).
hasForm(stone44,ball).
hasForm(wood14,bar).
hasForm(wood16,bar).
hasForm(wood20,bar).
hasForm(wood22,bar).
hasForm(wood28,bar).
hasForm(wood32,bar).
hasForm(wood4,bar).
hasForm(wood6,bar).
hasMaterial(ice10,glass).
hasMaterial(ice12,glass).
hasMaterial(ice18,glass).
hasMaterial(ice24,glass).
hasMaterial(ice26,glass).
hasMaterial(ice30,glass).
hasMaterial(ice34,glass).
hasMaterial(ice36,glass).
hasMaterial(ice8,glass).
hasMaterial(stone38,stone).
hasMaterial(stone40,stone).
hasMaterial(stone42,stone).
hasMaterial(stone44,stone).
hasMaterial(wood14,wood).
hasMaterial(wood16,wood).
hasMaterial(wood20,wood).
hasMaterial(wood22,wood).
hasMaterial(wood28,wood).
hasMaterial(wood32,wood).
hasMaterial(wood4,wood).
hasMaterial(wood6,wood).
hasOrientation(ice10,horizontal).
hasOrientation(ice12,vertical).
hasOrientation(ice18,vertical).
hasOrientation(ice24,horizontal).
hasOrientation(ice26,horizontal).
hasOrientation(ice30,vertical).
hasOrientation(ice34,horizontal).
hasOrientation(ice36,vertical).
hasOrientation(ice8,vertical).
hasOrientation(stone38,horizontal).
hasOrientation(stone40,horizontal).
hasOrientation(stone42,horizontal).
hasOrientation(stone44,horizontal).
hasOrientation(wood14,vertical).
hasOrientation(wood16,horizontal).
hasOrientation(wood20,vertical).
hasOrientation(wood22,horizontal).
hasOrientation(wood28,vertical).
hasOrientation(wood32,vertical).
hasOrientation(wood4,horizontal).
hasOrientation(wood6,vertical).
hasSize(ice10,big).
hasSize(ice12,medium).
hasSize(ice18,medium).
hasSize(ice24,big).
hasSize(ice26,medium).
hasSize(ice30,medium).
hasSize(ice34,big).
hasSize(ice36,medium).
hasSize(ice8,medium).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(pig2,medium).
hasSize(pig3,medium).
hasSize(stone38,medium).
hasSize(stone40,medium).
hasSize(stone42,medium).
hasSize(stone44,medium).
hasSize(wood14,big).
hasSize(wood16,big).
hasSize(wood20,big).
hasSize(wood22,big).
hasSize(wood28,big).
hasSize(wood32,big).
hasSize(wood4,big).
hasSize(wood6,big).
hill(hill1).
hill(hill2).
isAnchorPointFor(ice34,struct3).
isAnchorPointFor(ice36,struct4).
isAnchorPointFor(pig1,struct1).
isAnchorPointFor(pig2,struct2).
isAnchorPointFor(stone38,struct5).
isAnchorPointFor(wood4,struct0).
isBelow(ice10,ice12).
isBelow(ice12,ice8).
isBelow(ice12,pig0).
isBelow(ice12,wood22).
isBelow(ice12,wood4).
isBelow(ice24,ice26).
isBelow(ice26,wood22).
isBelow(ice26,wood4).
isBelow(stone40,stone42).
isBelow(stone42,stone44).
isBelow(wood14,wood16).
isBelow(wood16,ice18).
isBelow(wood20,wood22).
isBelow(wood20,wood4).
isBelow(wood22,ice30).
isBelow(wood22,pig0).
isBelow(wood22,wood28).
isBelow(wood28,wood16).
isBelow(wood32,wood22).
isBelow(wood4,ice8).
isBelow(wood4,pig0).
isBelow(wood4,wood14).
isBelow(wood6,wood4).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isHittable(ice10,true).
isHittable(ice12,true).
isHittable(ice18,true).
isHittable(ice30,true).
isHittable(ice34,true).
isHittable(ice8,true).
isHittable(pig1,true).
isHittable(pig3,true).
isHittable(stone38,true).
isHittable(wood16,true).
isHittable(wood22,true).
isHittable(wood4,true).
isHittable(wood6,true).
isLeft(ice10,wood20).
isLeft(ice12,wood20).
isLeft(ice18,wood28).
isLeft(ice24,wood32).
isLeft(ice26,wood32).
isLeft(ice34,stone40).
isLeft(ice8,wood14).
isLeft(pig0,wood28).
isLeft(pig2,pig3).
isLeft(wood14,ice18).
isLeft(wood14,pig0).
isLeft(wood20,ice24).
isLeft(wood20,ice26).
isLeft(wood28,ice30).
isLeft(wood4,wood22).
isLeft(wood6,ice10).
isLeft(wood6,ice12).
isOn(ice10,hill1).
isOn(ice12,ice10).
isOn(ice18,wood16).
isOn(ice24,hill1).
isOn(ice26,ice24).
isOn(ice30,wood22).
isOn(ice34,hill2).
isOn(ice36,hill2).
isOn(ice8,ice12).
isOn(ice8,wood4).
isOn(pig0,ice12).
isOn(pig0,wood22).
isOn(pig0,wood4).
isOn(pig1,hill2).
isOn(pig2,hill2).
isOn(pig3,hill2).
isOn(stone38,ground).
isOn(stone40,hill2).
isOn(stone42,stone40).
isOn(stone44,stone42).
isOn(wood14,wood4).
isOn(wood16,wood14).
isOn(wood16,wood28).
isOn(wood20,hill1).
isOn(wood22,ice12).
isOn(wood22,ice26).
isOn(wood22,wood20).
isOn(wood22,wood32).
isOn(wood28,wood22).
isOn(wood32,hill1).
isOn(wood4,ice12).
isOn(wood4,ice26).
isOn(wood4,wood20).
isOn(wood4,wood6).
isOn(wood6,hill1).
isOver(pig0,wood14).
isOver(pig1,ice10).
isOver(pig2,ice24).
isOver(pig3,wood32).
isOver(stone40,stone38).
isOver(stone42,stone44).
isRight(ice10,wood6).
isRight(ice12,wood6).
isRight(ice18,wood14).
isRight(ice24,wood20).
isRight(ice26,wood20).
isRight(ice30,wood28).
isRight(pig0,wood14).
isRight(pig3,pig2).
isRight(stone40,ice34).
isRight(wood14,ice8).
isRight(wood20,ice10).
isRight(wood20,ice12).
isRight(wood22,wood4).
isRight(wood28,ice18).
isRight(wood28,pig0).
isRight(wood32,ice24).
isRight(wood32,ice26).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
protects(struct0,pig1).
protects(struct0,pig2).
protects(struct0,pig3).
structure(struct0).
structure(struct1).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
supports(ice12,wood20).
supports(ice12,wood6).
supports(ice18,wood14).
supports(ice18,wood28).
supports(ice30,wood28).
supports(ice34,stone40).
supports(ice8,wood14).
supports(wood14,ice18).
supports(wood14,ice8).
supports(wood14,pig0).
supports(wood20,ice10).
supports(wood20,ice12).
supports(wood20,ice24).
supports(wood20,ice26).
supports(wood28,ice18).
supports(wood28,ice30).
supports(wood28,pig0).
supports(wood32,ice24).
supports(wood32,ice26).
supports(wood6,ice10).
supports(wood6,ice12).
