belongsTo(wood2,struct0).
belongsTo(pig0,struct1).
belongsTo(stone20,struct1).
belongsTo(wood16,struct1).
belongsTo(wood18,struct1).
belongsTo(wood22,struct1).
belongsTo(wood26,struct1).
belongsTo(wood28,struct1).
belongsTo(wood4,struct1).
belongsTo(wood6,struct1).
belongsTo(wood8,struct1).
belongsTo(ice14,struct2).
belongsTo(ice24,struct2).
belongsTo(wood10,struct2).
belongsTo(wood12,struct2).
bird(redbird1).
bird(redbird2).
bird(redbird3).
birdOrder(redbird1,2).
birdOrder(redbird2,1).
birdOrder(redbird3,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct2,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
hasColor(redbird1,red).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasForm(ice14,bar).
hasForm(ice24,bar).
hasForm(stone20,block).
hasForm(wood10,bar).
hasForm(wood12,bar).
hasForm(wood16,bar).
hasForm(wood18,bar).
hasForm(wood2,bar).
hasForm(wood22,bar).
hasForm(wood26,bar).
hasForm(wood28,bar).
hasForm(wood4,bar).
hasForm(wood6,bar).
hasForm(wood8,bar).
hasMaterial(ice14,glass).
hasMaterial(ice24,glass).
hasMaterial(stone20,stone).
hasMaterial(wood10,wood).
hasMaterial(wood12,wood).
hasMaterial(wood16,wood).
hasMaterial(wood18,wood).
hasMaterial(wood2,wood).
hasMaterial(wood22,wood).
hasMaterial(wood26,wood).
hasMaterial(wood28,wood).
hasMaterial(wood4,wood).
hasMaterial(wood6,wood).
hasMaterial(wood8,wood).
hasOrientation(ice14,vertical).
hasOrientation(ice24,vertical).
hasOrientation(stone20,vertical).
hasOrientation(wood10,horizontal).
hasOrientation(wood12,horizontal).
hasOrientation(wood16,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood2,vertical).
hasOrientation(wood22,vertical).
hasOrientation(wood26,vertical).
hasOrientation(wood28,vertical).
hasOrientation(wood4,horizontal).
hasOrientation(wood6,vertical).
hasOrientation(wood8,vertical).
hasSize(ice14,medium).
hasSize(ice24,medium).
hasSize(pig0,medium).
hasSize(stone20,medium).
hasSize(wood10,big).
hasSize(wood12,medium).
hasSize(wood16,big).
hasSize(wood18,small).
hasSize(wood2,small).
hasSize(wood22,small).
hasSize(wood26,big).
hasSize(wood28,big).
hasSize(wood4,big).
hasSize(wood6,big).
hasSize(wood8,big).
hill(dummyObject).
isAnchorPointFor(wood10,struct2).
isAnchorPointFor(wood2,struct0).
isAnchorPointFor(wood4,struct1).
isBelow(ice14,wood12).
isBelow(ice24,wood12).
isBelow(stone20,wood22).
isBelow(wood10,ice14).
isBelow(wood10,ice24).
isBelow(wood16,stone20).
isBelow(wood18,pig0).
isBelow(wood26,wood16).
isBelow(wood28,wood4).
isBelow(wood4,wood18).
isBelow(wood4,wood26).
isBelow(wood4,wood8).
isBelow(wood6,wood4).
isBelow(wood8,wood16).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isHittable(stone20,true).
isHittable(wood12,true).
isHittable(wood16,true).
isHittable(wood2,true).
isHittable(wood22,true).
isHittable(wood28,true).
isHittable(wood4,true).
isHittable(wood6,true).
isHittable(wood8,true).
isLeft(wood8,pig0).
isLeft(wood8,wood18).
isOn(ice14,wood10).
isOn(ice24,wood10).
isOn(pig0,wood18).
isOn(stone20,wood16).
isOn(wood10,ground).
isOn(wood12,ice14).
isOn(wood12,ice24).
isOn(wood16,wood26).
isOn(wood16,wood8).
isOn(wood18,wood4).
isOn(wood2,ground).
isOn(wood22,stone20).
isOn(wood26,wood4).
isOn(wood28,ground).
isOn(wood4,wood28).
isOn(wood4,wood6).
isOn(wood6,ground).
isOn(wood8,wood4).
isOver(pig0,wood8).
isRight(pig0,wood8).
isRight(wood18,wood8).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
pig(pig0).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct2).
supports(wood8,pig0).
supports(wood8,wood18).
