belongsTo(ice12,struct2).
belongsTo(ice14,struct2).
belongsTo(ice16,struct2).
belongsTo(ice18,struct2).
belongsTo(ice20,struct2).
belongsTo(ice22,struct2).
belongsTo(ice24,struct2).
belongsTo(ice46,struct4).
belongsTo(ice47,struct4).
belongsTo(ice55,struct4).
belongsTo(pig0,struct3).
belongsTo(pig1,struct3).
belongsTo(stone10,struct0).
belongsTo(stone37,struct3).
belongsTo(stone4,struct1).
belongsTo(stone6,struct1).
belongsTo(stone8,struct0).
belongsTo(wood2,struct0).
belongsTo(wood26,struct2).
belongsTo(wood28,struct3).
belongsTo(wood30,struct3).
belongsTo(wood32,struct3).
belongsTo(wood34,struct3).
belongsTo(wood36,struct3).
belongsTo(wood39,struct3).
belongsTo(wood41,struct3).
belongsTo(wood43,struct3).
belongsTo(wood45,struct3).
belongsTo(wood49,struct5).
belongsTo(wood50,struct6).
belongsTo(wood52,struct7).
belongsTo(wood53,struct7).
belongsTo(wood57,struct8).
belongsTo(wood59,struct9).
belongsTo(wood64,struct10).
belongsTo(wood65,struct11).
belongsTo(wood67,struct10).
belongsTo(wood68,struct12).
belongsTo(wood70,struct13).
bird(bluebird8).
bird(redbird2).
bird(redbird3).
bird(redbird4).
bird(redbird5).
bird(redbird6).
bird(yellowbird7).
birdOrder(bluebird8,4).
birdOrder(redbird2,5).
birdOrder(redbird3,2).
birdOrder(redbird4,0).
birdOrder(redbird5,1).
birdOrder(redbird6,3).
birdOrder(yellowbird7,6).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct1,struct2).
canCollapse(struct10,struct11).
canCollapse(struct10,struct9).
canCollapse(struct11,struct10).
canCollapse(struct12,struct13).
canCollapse(struct13,struct12).
canCollapse(struct2,struct3).
canCollapse(struct3,struct4).
canCollapse(struct4,struct5).
canCollapse(struct5,struct4).
canCollapse(struct5,struct6).
canCollapse(struct6,struct5).
canCollapse(struct6,struct7).
canCollapse(struct7,struct6).
canCollapse(struct8,struct9).
canCollapse(struct9,struct10).
canCollapse(struct9,struct8).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct10,struct11,away).
collapsesInDirection(struct10,struct9,towards).
collapsesInDirection(struct11,struct10,towards).
collapsesInDirection(struct11,struct12,away).
collapsesInDirection(struct12,struct11,towards).
collapsesInDirection(struct12,struct13,away).
collapsesInDirection(struct13,struct12,towards).
collapsesInDirection(struct2,struct1,towards).
collapsesInDirection(struct2,struct3,away).
collapsesInDirection(struct3,struct2,towards).
collapsesInDirection(struct3,struct4,away).
collapsesInDirection(struct4,struct3,towards).
collapsesInDirection(struct4,struct5,away).
collapsesInDirection(struct5,struct4,towards).
collapsesInDirection(struct5,struct6,away).
collapsesInDirection(struct6,struct5,towards).
collapsesInDirection(struct6,struct7,away).
collapsesInDirection(struct7,struct6,towards).
collapsesInDirection(struct7,struct8,away).
collapsesInDirection(struct8,struct7,towards).
collapsesInDirection(struct8,struct9,away).
collapsesInDirection(struct9,struct10,away).
collapsesInDirection(struct9,struct8,towards).
hasColor(bluebird8,blue).
hasColor(redbird2,red).
hasColor(redbird3,red).
hasColor(redbird4,red).
hasColor(redbird5,red).
hasColor(redbird6,red).
hasColor(yellowbird7,yellow).
hasForm(ice12,bar).
hasForm(ice14,block).
hasForm(ice16,block).
hasForm(ice18,block).
hasForm(ice20,block).
hasForm(ice22,block).
hasForm(ice24,cube).
hasForm(ice46,block).
hasForm(ice47,bar).
hasForm(ice55,bar).
hasForm(stone10,bar).
hasForm(stone37,block).
hasForm(stone4,bar).
hasForm(stone6,bar).
hasForm(stone8,bar).
hasForm(wood2,bar).
hasForm(wood26,block).
hasForm(wood28,bar).
hasForm(wood30,bar).
hasForm(wood32,bar).
hasForm(wood34,block).
hasForm(wood36,block).
hasForm(wood39,block).
hasForm(wood41,block).
hasForm(wood43,block).
hasForm(wood45,block).
hasForm(wood49,bar).
hasForm(wood50,bar).
hasForm(wood52,bar).
hasForm(wood53,bar).
hasForm(wood57,bar).
hasForm(wood59,bar).
hasForm(wood64,block).
hasForm(wood65,block).
hasForm(wood67,cube).
hasForm(wood68,bar).
hasForm(wood70,bar).
hasMaterial(ice12,glass).
hasMaterial(ice14,glass).
hasMaterial(ice16,glass).
hasMaterial(ice18,glass).
hasMaterial(ice20,glass).
hasMaterial(ice22,glass).
hasMaterial(ice24,glass).
hasMaterial(ice46,glass).
hasMaterial(ice47,glass).
hasMaterial(ice55,glass).
hasMaterial(stone10,stone).
hasMaterial(stone37,stone).
hasMaterial(stone4,stone).
hasMaterial(stone6,stone).
hasMaterial(stone8,stone).
hasMaterial(wood2,wood).
hasMaterial(wood26,wood).
hasMaterial(wood28,wood).
hasMaterial(wood30,wood).
hasMaterial(wood32,wood).
hasMaterial(wood34,wood).
hasMaterial(wood36,wood).
hasMaterial(wood39,wood).
hasMaterial(wood41,wood).
hasMaterial(wood43,wood).
hasMaterial(wood45,wood).
hasMaterial(wood49,wood).
hasMaterial(wood50,wood).
hasMaterial(wood52,wood).
hasMaterial(wood53,wood).
hasMaterial(wood57,wood).
hasMaterial(wood59,wood).
hasMaterial(wood64,wood).
hasMaterial(wood65,wood).
hasMaterial(wood67,wood).
hasMaterial(wood68,wood).
hasMaterial(wood70,wood).
hasOrientation(ice12,horizontal).
hasOrientation(ice14,horizontal).
hasOrientation(ice16,horizontal).
hasOrientation(ice18,horizontal).
hasOrientation(ice20,horizontal).
hasOrientation(ice22,horizontal).
hasOrientation(ice24,horizontal).
hasOrientation(ice46,horizontal).
hasOrientation(ice47,horizontal).
hasOrientation(ice55,horizontal).
hasOrientation(stone10,vertical).
hasOrientation(stone37,horizontal).
hasOrientation(stone4,vertical).
hasOrientation(stone6,vertical).
hasOrientation(stone8,vertical).
hasOrientation(wood2,horizontal).
hasOrientation(wood26,horizontal).
hasOrientation(wood28,horizontal).
hasOrientation(wood30,horizontal).
hasOrientation(wood32,horizontal).
hasOrientation(wood34,horizontal).
hasOrientation(wood36,horizontal).
hasOrientation(wood39,horizontal).
hasOrientation(wood41,horizontal).
hasOrientation(wood43,horizontal).
hasOrientation(wood45,horizontal).
hasOrientation(wood49,horizontal).
hasOrientation(wood50,horizontal).
hasOrientation(wood52,horizontal).
hasOrientation(wood53,horizontal).
hasOrientation(wood57,horizontal).
hasOrientation(wood59,horizontal).
hasOrientation(wood64,vertical).
hasOrientation(wood65,horizontal).
hasOrientation(wood67,horizontal).
hasOrientation(wood68,horizontal).
hasOrientation(wood70,horizontal).
hasSize(ice12,big).
hasSize(ice14,medium).
hasSize(ice16,medium).
hasSize(ice18,medium).
hasSize(ice20,medium).
hasSize(ice22,medium).
hasSize(ice24,big).
hasSize(ice46,medium).
hasSize(ice47,big).
hasSize(ice55,big).
hasSize(pig0,medium).
hasSize(pig1,medium).
hasSize(stone10,big).
hasSize(stone37,medium).
hasSize(stone4,big).
hasSize(stone6,big).
hasSize(stone8,big).
hasSize(wood2,big).
hasSize(wood26,medium).
hasSize(wood28,big).
hasSize(wood30,big).
hasSize(wood32,big).
hasSize(wood34,medium).
hasSize(wood36,medium).
hasSize(wood39,medium).
hasSize(wood41,medium).
hasSize(wood43,medium).
hasSize(wood45,medium).
hasSize(wood49,big).
hasSize(wood50,big).
hasSize(wood52,big).
hasSize(wood53,big).
hasSize(wood57,big).
hasSize(wood59,big).
hasSize(wood64,medium).
hasSize(wood65,medium).
hasSize(wood67,big).
hasSize(wood68,big).
hasSize(wood70,big).
hill(dummyObject).
isAnchorPointFor(ice14,struct2).
isAnchorPointFor(ice46,struct4).
isAnchorPointFor(stone4,struct1).
isAnchorPointFor(wood2,struct0).
isAnchorPointFor(wood28,struct3).
isAnchorPointFor(wood49,struct5).
isAnchorPointFor(wood50,struct6).
isAnchorPointFor(wood52,struct7).
isAnchorPointFor(wood57,struct8).
isAnchorPointFor(wood59,struct9).
isAnchorPointFor(wood64,struct10).
isAnchorPointFor(wood65,struct11).
isAnchorPointFor(wood68,struct12).
isAnchorPointFor(wood70,struct13).
isBelow(ice12,ice14).
isBelow(ice12,ice18).
isBelow(ice16,ice14).
isBelow(ice16,ice18).
isBelow(ice16,ice20).
isBelow(ice22,ice18).
isBelow(ice22,ice20).
isBelow(ice24,ice20).
isBelow(pig0,stone37).
isBelow(pig1,wood34).
isBelow(stone10,wood2).
isBelow(stone4,stone6).
isBelow(stone8,stone10).
isBelow(wood28,pig1).
isBelow(wood28,wood32).
isBelow(wood30,pig1).
isBelow(wood30,wood32).
isBelow(wood30,wood41).
isBelow(wood32,wood34).
isBelow(wood32,wood43).
isBelow(wood34,wood36).
isBelow(wood34,wood45).
isBelow(wood36,pig0).
isBelow(wood39,wood32).
isBelow(wood39,wood41).
isBelow(wood41,wood34).
isBelow(wood41,wood43).
isBelow(wood43,wood36).
isBelow(wood43,wood45).
isBelow(wood45,pig0).
isBelow(wood67,wood64).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct10).
isCollapsable(struct11).
isCollapsable(struct12).
isCollapsable(struct13).
isCollapsable(struct2).
isCollapsable(struct3).
isCollapsable(struct4).
isCollapsable(struct5).
isCollapsable(struct6).
isCollapsable(struct7).
isCollapsable(struct8).
isCollapsable(struct9).
isHittable(ice12,true).
isHittable(ice14,true).
isHittable(ice16,true).
isHittable(ice18,true).
isHittable(ice20,true).
isHittable(ice22,true).
isHittable(ice24,true).
isHittable(pig0,true).
isHittable(pig1,true).
isHittable(stone37,true).
isHittable(stone4,true).
isHittable(stone6,true).
isHittable(stone8,true).
isHittable(wood2,true).
isHittable(wood26,true).
isHittable(wood28,true).
isHittable(wood30,true).
isHittable(wood32,true).
isHittable(wood34,true).
isHittable(wood36,true).
isHittable(wood50,true).
isHittable(wood52,true).
isHittable(wood53,true).
isLeft(ice12,ice16).
isLeft(ice14,ice18).
isLeft(ice16,ice22).
isLeft(ice18,ice20).
isLeft(ice22,ice24).
isLeft(ice22,wood26).
isLeft(ice46,ice55).
isLeft(ice47,ice55).
isLeft(pig1,wood32).
isLeft(wood28,wood30).
isLeft(wood30,wood39).
isLeft(wood32,wood41).
isLeft(wood34,wood43).
isLeft(wood36,wood45).
isLeft(wood52,wood53).
isOn(ice12,ground).
isOn(ice14,ice12).
isOn(ice14,ice16).
isOn(ice16,ground).
isOn(ice18,ice12).
isOn(ice18,ice16).
isOn(ice18,ice22).
isOn(ice20,ice16).
isOn(ice20,ice22).
isOn(ice20,ice24).
isOn(ice22,ground).
isOn(ice24,ground).
isOn(ice46,ground).
isOn(ice47,ground).
isOn(ice55,ground).
isOn(pig0,wood36).
isOn(pig0,wood45).
isOn(pig1,wood28).
isOn(pig1,wood30).
isOn(stone10,stone8).
isOn(stone37,pig0).
isOn(stone4,ground).
isOn(stone6,stone4).
isOn(stone8,ground).
isOn(wood2,stone10).
isOn(wood26,ground).
isOn(wood28,ground).
isOn(wood30,ground).
isOn(wood32,wood28).
isOn(wood32,wood30).
isOn(wood32,wood39).
isOn(wood34,pig1).
isOn(wood34,wood32).
isOn(wood34,wood41).
isOn(wood36,wood34).
isOn(wood36,wood43).
isOn(wood39,ground).
isOn(wood41,wood30).
isOn(wood41,wood39).
isOn(wood43,wood32).
isOn(wood43,wood41).
isOn(wood45,wood34).
isOn(wood45,wood43).
isOn(wood49,ground).
isOn(wood50,ground).
isOn(wood52,ground).
isOn(wood53,ground).
isOn(wood57,ground).
isOn(wood59,ground).
isOn(wood64,wood67).
isOn(wood65,ground).
isOn(wood67,ground).
isOn(wood68,ground).
isOn(wood70,ground).
isOver(pig0,stone37).
isOver(pig1,wood32).
isRight(ice16,ice12).
isRight(ice18,ice14).
isRight(ice20,ice18).
isRight(ice22,ice16).
isRight(ice24,ice22).
isRight(ice55,ice46).
isRight(ice55,ice47).
isRight(wood26,ice22).
isRight(wood30,wood28).
isRight(wood32,pig1).
isRight(wood39,wood30).
isRight(wood41,wood32).
isRight(wood43,wood34).
isRight(wood45,wood36).
isRight(wood53,wood52).
object(X) :- hasMaterial(X,_).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
protects(dummyObject,dummmyObject).
structure(struct0).
structure(struct1).
structure(struct10).
structure(struct11).
structure(struct12).
structure(struct13).
structure(struct2).
structure(struct3).
structure(struct4).
structure(struct5).
structure(struct6).
structure(struct7).
structure(struct8).
structure(struct9).
supports(ice16,ice12).
supports(ice16,ice22).
supports(wood26,ice22).
