belongsTo(ice25,struct2).
belongsTo(pig0,struct0).
belongsTo(pig1,struct1).
belongsTo(pig2,struct0).
belongsTo(pig3,struct0).
belongsTo(wood0,struct0).
belongsTo(wood1,struct0).
belongsTo(wood10,struct0).
belongsTo(wood11,struct0).
belongsTo(wood12,struct0).
belongsTo(wood13,struct0).
belongsTo(wood14,struct0).
belongsTo(wood15,struct0).
belongsTo(wood16,struct0).
belongsTo(wood17,struct0).
belongsTo(wood18,struct0).
belongsTo(wood19,struct0).
belongsTo(wood2,struct0).
belongsTo(wood20,struct0).
belongsTo(wood21,struct0).
belongsTo(wood22,struct0).
belongsTo(wood23,struct0).
belongsTo(wood24,struct0).
belongsTo(wood3,struct0).
belongsTo(wood4,struct0).
belongsTo(wood5,struct0).
belongsTo(wood6,struct0).
belongsTo(wood7,struct0).
belongsTo(wood8,struct0).
belongsTo(wood9,struct0).
bird(whitebird4).
bird(yellowbird0).
bird(yellowbird1).
bird(yellowbird2).
bird(yellowbird3).
bird(yellowbird5).
birdOrder(whitebird4,1).
birdOrder(yellowbird0,2).
birdOrder(yellowbird1,3).
birdOrder(yellowbird2,4).
birdOrder(yellowbird3,5).
birdOrder(yellowbird5,0).
canCollapse(struct0,struct1).
canCollapse(struct1,struct0).
canCollapse(struct2,struct1).
canExplode(dummyObject,dummmyObject).
collapsesInDirection(struct0,struct1,away).
collapsesInDirection(struct1,struct0,towards).
collapsesInDirection(struct1,struct2,away).
collapsesInDirection(struct2,struct1,towards).
hasColor(whitebird4,white).
hasColor(yellowbird0,yellow).
hasColor(yellowbird1,yellow).
hasColor(yellowbird2,yellow).
hasColor(yellowbird3,yellow).
hasColor(yellowbird5,yellow).
hasForm(ice25,cube).
hasForm(wood0,bar).
hasForm(wood1,block).
hasForm(wood10,bar).
hasForm(wood11,block).
hasForm(wood12,bar).
hasForm(wood13,bar).
hasForm(wood14,bar).
hasForm(wood15,bar).
hasForm(wood16,bar).
hasForm(wood17,bar).
hasForm(wood18,cube).
hasForm(wood19,block).
hasForm(wood2,cube).
hasForm(wood20,bar).
hasForm(wood21,cube).
hasForm(wood22,block).
hasForm(wood23,block).
hasForm(wood24,block).
hasForm(wood3,block).
hasForm(wood4,bar).
hasForm(wood5,cube).
hasForm(wood6,bar).
hasForm(wood7,bar).
hasForm(wood8,block).
hasForm(wood9,bar).
hasMaterial(ice25,glass).
hasMaterial(wood0,wood).
hasMaterial(wood1,wood).
hasMaterial(wood10,wood).
hasMaterial(wood11,wood).
hasMaterial(wood12,wood).
hasMaterial(wood13,wood).
hasMaterial(wood14,wood).
hasMaterial(wood15,wood).
hasMaterial(wood16,wood).
hasMaterial(wood17,wood).
hasMaterial(wood18,wood).
hasMaterial(wood19,wood).
hasMaterial(wood2,wood).
hasMaterial(wood20,wood).
hasMaterial(wood21,wood).
hasMaterial(wood22,wood).
hasMaterial(wood23,wood).
hasMaterial(wood24,wood).
hasMaterial(wood3,wood).
hasMaterial(wood4,wood).
hasMaterial(wood5,wood).
hasMaterial(wood6,wood).
hasMaterial(wood7,wood).
hasMaterial(wood8,wood).
hasMaterial(wood9,wood).
hasOrientation(ice25,horizontal).
hasOrientation(wood0,vertical).
hasOrientation(wood1,vertical).
hasOrientation(wood10,horizontal).
hasOrientation(wood11,vertical).
hasOrientation(wood12,vertical).
hasOrientation(wood13,vertical).
hasOrientation(wood14,vertical).
hasOrientation(wood15,horizontal).
hasOrientation(wood16,horizontal).
hasOrientation(wood17,horizontal).
hasOrientation(wood18,horizontal).
hasOrientation(wood19,vertical).
hasOrientation(wood2,horizontal).
hasOrientation(wood20,horizontal).
hasOrientation(wood21,horizontal).
hasOrientation(wood22,vertical).
hasOrientation(wood23,vertical).
hasOrientation(wood24,vertical).
hasOrientation(wood3,vertical).
hasOrientation(wood4,horizontal).
hasOrientation(wood5,horizontal).
hasOrientation(wood6,horizontal).
hasOrientation(wood7,horizontal).
hasOrientation(wood8,vertical).
hasOrientation(wood9,horizontal).
hasSize(ice25,small).
hasSize(pig0,small).
hasSize(pig1,small).
hasSize(pig2,small).
hasSize(pig3,small).
hasSize(wood0,medium).
hasSize(wood1,medium).
hasSize(wood10,big).
hasSize(wood11,medium).
hasSize(wood12,small).
hasSize(wood13,medium).
hasSize(wood14,medium).
hasSize(wood15,big).
hasSize(wood16,big).
hasSize(wood17,big).
hasSize(wood18,small).
hasSize(wood19,medium).
hasSize(wood2,small).
hasSize(wood20,medium).
hasSize(wood21,small).
hasSize(wood22,medium).
hasSize(wood23,medium).
hasSize(wood24,medium).
hasSize(wood3,medium).
hasSize(wood4,big).
hasSize(wood5,small).
hasSize(wood6,big).
hasSize(wood7,big).
hasSize(wood8,medium).
hasSize(wood9,big).
hill(hill0).
isAnchorPointFor(ice25,struct2).
isAnchorPointFor(pig1,struct1).
isAnchorPointFor(wood1,struct0).
isBelow(pig3,wood15).
isBelow(wood0,wood1).
isBelow(wood1,wood4).
isBelow(wood10,wood17).
isBelow(wood10,wood4).
isBelow(wood12,wood6).
isBelow(wood13,wood9).
isBelow(wood14,wood15).
isBelow(wood15,wood16).
isBelow(wood16,wood11).
isBelow(wood16,wood18).
isBelow(wood16,wood21).
isBelow(wood17,pig3).
isBelow(wood17,wood14).
isBelow(wood17,wood22).
isBelow(wood19,wood20).
isBelow(wood2,wood6).
isBelow(wood20,wood17).
isBelow(wood22,wood23).
isBelow(wood23,wood15).
isBelow(wood24,wood20).
isBelow(wood4,pig0).
isBelow(wood4,wood12).
isBelow(wood4,wood5).
isBelow(wood5,wood2).
isBelow(wood6,wood7).
isBelow(wood7,wood11).
isBelow(wood7,wood3).
isBelow(wood7,wood8).
isBelow(wood9,wood10).
isCollapsable(struct0).
isCollapsable(struct1).
isCollapsable(struct2).
isHittable(wood0,true).
isHittable(wood1,true).
isHittable(wood11,true).
isHittable(wood15,true).
isHittable(wood16,true).
isHittable(wood18,true).
isHittable(wood2,true).
isHittable(wood21,true).
isHittable(wood3,true).
isHittable(wood4,true).
isHittable(wood5,true).
isHittable(wood6,true).
isHittable(wood7,true).
isHittable(wood8,true).
isLeft(wood1,wood10).
isLeft(wood1,wood9).
isLeft(wood10,wood20).
isLeft(wood12,wood14).
isLeft(wood13,pig2).
isLeft(wood19,wood24).
isLeft(wood2,pig0).
isLeft(wood4,wood17).
isLeft(wood5,pig0).
isLeft(wood6,wood15).
isLeft(wood6,wood16).
isLeft(wood7,wood16).
isLeft(wood9,wood20).
isOn(ice25,ground).
isOn(pig0,wood4).
isOn(pig1,hill0).
isOn(pig2,hill0).
isOn(pig3,wood17).
isOn(wood0,hill0).
isOn(wood1,wood0).
isOn(wood10,wood9).
isOn(wood11,wood16).
isOn(wood11,wood7).
isOn(wood12,wood4).
isOn(wood13,hill0).
isOn(wood14,wood17).
isOn(wood15,pig3).
isOn(wood15,wood14).
isOn(wood15,wood23).
isOn(wood16,wood15).
isOn(wood17,wood10).
isOn(wood17,wood20).
isOn(wood18,wood16).
isOn(wood19,hill0).
isOn(wood2,wood5).
isOn(wood20,wood19).
isOn(wood20,wood24).
isOn(wood21,wood16).
isOn(wood22,wood17).
isOn(wood23,wood22).
isOn(wood24,hill0).
isOn(wood3,wood7).
isOn(wood4,wood1).
isOn(wood4,wood10).
isOn(wood5,wood4).
isOn(wood6,wood12).
isOn(wood6,wood2).
isOn(wood7,wood6).
isOn(wood8,wood7).
isOn(wood9,wood13).
isOver(pig0,wood2).
isOver(pig1,wood9).
isOver(pig2,wood13).
isOver(pig3,wood23).
isRight(pig0,wood2).
isRight(pig0,wood5).
isRight(pig2,wood13).
isRight(wood10,wood1).
isRight(wood14,wood12).
isRight(wood15,wood6).
isRight(wood16,wood6).
isRight(wood16,wood7).
isRight(wood17,wood4).
isRight(wood20,wood10).
isRight(wood20,wood9).
isRight(wood24,wood19).
isRight(wood9,wood1).
object(X) :- hasMaterial(X,_).
object(X) :- hill(X).
object(X) :- pig(X).
pig(pig0).
pig(pig1).
pig(pig2).
pig(pig3).
protects(struct0,pig1).
structure(struct0).
structure(struct1).
structure(struct2).
supports(wood12,wood14).
supports(wood13,pig2).
supports(wood14,wood12).
supports(wood19,wood24).
supports(wood24,wood19).